### ISSUE TITLE
certs can't contact things svc lacking proper configuration

### ISSUE THREAD

**Issue by smartyfi** [Mainflux/mainflux-lite#1468]
Hi,
I'm trying to run certs with vault to generate certificates

calling 
curl -s -S  -X POST  http://localhost:8204/certs -H "Authorization: $TOK" -H 'Content-Type: application/json'   -d '{"thing_id":"5ed91a85-a325-458c-b816-aacde1472b38", "rsa_bits":2048, "key_type":"rsa"}'

getting the below error
{"level":"warn","message":"Method issue_cert for token: xxxxx and thing: 5ed91a85-a325-458c-b816-aacde1472b38 took 1.6573ms to complete with error: failed to create client certificate : Get \"/things/5ed91a85-a325-458c-b816-aacde1472b38\": unsupported protocol scheme \"\".","ts":"2021-10-05T22:47:26.8411872Z"}

after reviewing the source code for certs it looks like initializing the sdk doesn't pass the thingsURL

func newService(auth mainflux.AuthServiceClient, db *sqlx.DB, logger mflog.Logger, esClient *redis.Client, tlsCert tls.Certificate, x509Cert *x509.Certificate, cfg config, pkiAgent vault.Agent) certs.Service {
........
	config := mfsdk.Config{
		CertsURL: cfg.certsURL,
	}
i fixed to be, also had to add a few lines to get the ThingsURL from Environment Variables
	config := mfsdk.Config{
		CertsURL: cfg.certsURL,
		ThingsURL: cfg.thingsURL,
	}
and it works now , is this a bug ? should i submit a PR to fix ?

**Comment by drasko** [comment]
We did some changes recently with SDK, to make it independent of external base URL and usable within the private network behind the proxy.

However, this might have introduced some regression.

You'll probably have to debug around this URL issue with latest Certs and SDK, and please send PR if you find a solution ;).

**Comment by smartyfi** [comment]
yes I noticed that change in SDK it looks like a better strategy to communicate directly between components without going through the proxy , 
yes I managed to resolve the issue, but now I'm tracing another similar issue in provisioning svc will fix it and submit a PR,
looks like a great project so far, thanks guys, I wonder it does not get the proper attention it worth
