### ISSUE TITLE
Migration of old Things

### ISSUE THREAD

**Issue by buraksekili** [Mainflux/mainflux-lite#1490]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Since the policies do not use the `owner` field of Things, the old Things defined under the previous Mainflux (the version before policy implementation) have problems with policies (listing, ownership, etc.). Therefore, the migration has to be handled thoroughly.
3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
must-have

**Comment by dborovcanin** [comment]
This issue is almost 3y old now. It's a big effort and it's not worth our time unless we have someone facing this problem. In that case, please reopen or create a new ticket.
