### ISSUE TITLE
Event sourcing for groups

### ISSUE THREAD

**Issue by corp0529** [Mainflux/mainflux-lite#1510]
**FEATURE REQUEST**

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Add event sourcing to groups.  

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
should-have

This would work in the same way as event sourcing for things, using Redis Streams for all of the appropriate operations made on groups.

**Comment by dborovcanin** [comment]
Thanks for the feedback. This will be added as a part of #1506.
