### ISSUE TITLE
Password recovery e-mail headers get escaped with HTML

### ISSUE THREAD

**Issue by ghost** [Mainflux/mainflux-lite#1521]
This issue was found during deployment of the users service in [Orb](https://getorb.io/), using [AWS SES](https://aws.amazon.com/ses/) with a DKIM verified domain.

Since the [emailer class uses an HTML parser](https://github.com/mainflux/mainflux/blob/0fe9f55bae8d0887d5ea2d7be9fb483c6b0bfafc/internal/email/email.go#L9) to fill in the template with values, we get two errors:
1- The recipients list is converted to an array-like string, which contains invalid chars for SMTP
2- If a sender name + email is added, special characters are escaped to be HTML safe, which become invalid chars for SMTP.

Template [used by Mainflux:](https://github.com/mainflux/mainflux/blob/master/docker/templates/users.tmpl)
```
To: {{.To}}
From: {{.From}}
Subject: {{.Subject}}
{{.Header}}
You have initiated password reset.
Follow the link below to reset password.
{{.Content}}
{{.Footer}}
```
Input similar to what's used in [email.go](https://github.com/mainflux/mainflux/blob/0fe9f55bae8d0887d5ea2d7be9fb483c6b0bfafc/internal/email/email.go#L83):
```go
emailValues := emailTemplateStruct{
    To:      []string{"user1@test.com", "user2@test.com"},
    From:    "Orb <noreply@orb.live>",
    Subject: "Password Reset",
    Header:  "",
    Content: "https://orb.live//reset-request?token=123456",
    Footer:  "",
}
```
Example output:
```
To: [user1@test.com user2@test.com]
From: Orb &lt;noreply@orb.live&gt;
Subject: Password Reset

You have initiated password reset.
Follow the link below to reset password.
https://orb.live//reset-request?token=123456
```
Expected output:
```
To: user1@test.com user2@test.com
From: Orb <noreply@dev.orb.live>
Subject: Password Reset

You have initiated password reset.
Follow the link below to reset password.
https://orb.live//reset-request?token=123456
```

The first issue (recipients) causes this error: `554 Transaction failed: Illegal address`
The second issue (sender) causes this error: `554 Transaction failed: Illegal semicolon, not in group`
If only sender name is provided as part of `MF_EMAIL_FROM_NAME` env var (i.e. "Orb"), we get `554 Transaction failed: User name is missing: 'Orb'.`

**Comment by drasko** [comment]
@blokovi please take a look at this one.

**Comment by blokovi** [comment]
Hi @stefano-daitan , thanks for submitting this bug.
With the latest commit, both these issues should be fixed. Please let us know if there is still some problem.
And you can now use env variables for FROM header in the usual way, something like this:
```
MF_EMAIL_FROM_ADDRESS=noreply@dev.orb.live
MF_EMAIL_FROM_NAME=Orb Dev
```

**Comment by ghost** [comment]
I confirm it's now working as expected, thank you @blokovi.
