### ISSUE TITLE
Consider using Go native error groups in main functions

### ISSUE THREAD

**Issue by dborovcanin** [Mainflux/mainflux-lite#1525]
**ENHANCEMENT**
1. Describe the enhancement you are requesting.
Consider using Go errors group (`golang.org/x/sync/errgroup`) for handling routines in `main` functions of Mainflux services.

2. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).
This is a nice-to-have.

**Comment by arvindh123** [comment]
In error groups , 
The function  `func (g *Group) Go(f func() error)` required return of error, 
It can't be a infinite loop 
So we need to change the way of starting `HTTP Server` and `GRPC Server`

At present , we are starting HTTP server as blocking code 
` func http.ListenAndServeTLS(addr string, certFile string, keyFile string, handler http.Handler) error`

Inorder to use error groups  `func (g *Group) Go(f func() error)` , we need to change the HTTP Server to a non blocking in two ways 

1.  Running the `func http.ListenAndServeTLS(addr string, certFile string, keyFile string, handler http.Handler) error` in another goroutine and waiting for error through a channel  , 

```
func startHTTPServer(ctx context.Context, tracer opentracing.Tracer, svc auth.Service, port string, certFile string, keyFile string, logger logger.Logger) error {
	p := fmt.Sprintf(":%s", port)
	errs := make(chan error, 1)
	if certFile != "" || keyFile != "" {
		logger.Info(fmt.Sprintf("Authentication service started using https, cert %s key %s, exposed port %s", certFile, keyFile, port))
		go func() {
			errs <- http.ListenAndServeTLS(p, certFile, keyFile, httpapi.MakeHandler(svc, tracer))
		}()
	} else {
		logger.Info(fmt.Sprintf("Authentication service started using http, exposed port %s", port))
		go func() {
			errs <- http.ListenAndServe(p, httpapi.MakeHandler(svc, tracer))
		}()
	}

	select {
	case <-ctx.Done():
		return nil
	case e := <-errs:
		return e
	}
}
```

2.  Start the HTTP Server with `http.Server`  with function  `func (*http.Server).ListenAndServeTLS(certFile string, keyFile string) error` in another goroutine and wait for error through a channel 
In this method we can gracefully stop the HTTP Server through function `func (*http.Server).Shutdown(ctx context.Context) error`
```
func startHTTPServer(ctx context.Context, tracer opentracing.Tracer, svc auth.Service, port string, certFile string, keyFile string, logger logger.Logger) error {
	server := &http.Server{Addr: fmt.Sprintf(":%s", port), Handler: httpapi.MakeHandler(svc, tracer)}
	errCh := make(chan error)
	if certFile != "" || keyFile != "" {
		logger.Info(fmt.Sprintf("Authentication service started using https, cert %s key %s, exposed port %s", certFile, keyFile, port))
		go func() {
			errCh <- server.ListenAndServeTLS(certFile, keyFile)
		}()
	} else {
		logger.Info(fmt.Sprintf("Authentication service started using http, exposed port %s", port))
		go func() {
			errCh <- server.ListenAndServe()
		}()
	}

	err := CatchErr(ctx, errCh)
	if err := server.Shutdown(context.Background()); err != nil {
		return err
	}
	return err
}

func CatchErr(ctx context.Context, err <-chan error) error {
	select {
	case e := <-err:
		return e
	case <-ctx.Done():
		return nil
	}
}

``` 


But in the two methods we need a error channel within the function `startHTTPServer`
Just the error channel from the `main()` function moved to the `startHTTPServer` 
For me It feel like adding more error channel variable to HTTP Server and GRPC Server . 
Its better to return the as error channel from function `startHTTPServer` and `startGRPCServer` , which the present code does, 

At present HTTP Server is start like this 

```
go startHTTPServer(tracer, svc, cfg.httpPort, cfg.serverCert, cfg.serverKey, logger, errs)
```
But to start the function via error group will be like 

```
g.Go(func() error {
		return startHTTPServer(ctx, tracer, svc, cfg.httpPort, cfg.serverCert, cfg.serverKey, logger)
	})
```
The `errs` channel is changed as `error` variable in error groups , but the is requirement of `errs` channels within the `startHTTPServer`
Feel like just the `errs` channel move from `main` function to `startHTTPServer` ,  `startGRPCServer`
At present cannot able to get better way for `errs` channel

**Comment by dborovcanin** [comment]
So, looks like native error groups bring nothing to the table.
@arvindh123 Is it possible to only add this HTTP server graceful shutdown and keep the error handling we are using currently?

**Comment by arvindh123** [comment]
@dusanb94 , Yeah its doable

**Comment by dborovcanin** [comment]
OK, let's proceed that way, only add graceful HTTP server shutdown.

**Comment by manuio** [comment]
@dusanb94 @arvindh123 Should we mention this issue in the PR https://github.com/mainflux/mainflux/pull/1548 ?

**Comment by dborovcanin** [comment]
@manuio Definitely, this should be closed in that PR.
