### ISSUE TITLE
Can't read the messages

### ISSUE THREAD

**Issue by digoptical22** [Mainflux/mainflux-lite#1527]
hi guys, i try to follow the documentation and syntax read messages error!!
![image](https://user-images.githubusercontent.com/58322053/145678035-be6c7859-34ad-424d-9084-b46c348c1293.png)

**Comment by dborovcanin** [comment]
@digoptical22 **Please respect issue template**. When closing an issue, please explain how you resolved it and what was the root cause, because it might be useful for the community.

**Comment by digoptical22** [comment]
Sorry, I didn't see anyone reply, so I closed it. do you know why i am getting such error??? @dusanb94

**Comment by dborovcanin** [comment]
Please send more logs from Writer and Reader.

**Comment by digoptical22** [comment]
oh, I solved this problem by using mqtt to send and receive messages. 
the command i use is
mosquitto_pub -u 40816461-a2d6-402e-8d95-5a2cd2646735 -P 235f56fc-7f67-4749-aa94-5c9e172b0657 -t channels/82f9131e-dc40-4bfe-8ab4-9ff52207ca9b/messages -h localhost -m '[{"bn":"some-base-name:","bt":1.276020076001e+09, "bu":"A","bver":5, "n":"voltage","u":"V","v":120.1}, {"n":"current","t":-5,"v":1.2}, {"n":"current","t":-4,"v":1.3}]'
and 
mosquitto_sub -u fcd4c722-b77a-45f0-a6d8-696245bee30a -P f1d812ca-d826-48c6-a10c-488ed79f5fb4 -t channels/82f9131e-dc40-4bfe-8ab4-9ff52207ca9b/messages -h localhost

[Reference links](https://medium.com/mainflux-iot-platform/quicktest-mainflux-mqtt-messaging-679ec1cce1b7)
