### ISSUE TITLE
can't register and login with mainflux ui

### ISSUE THREAD

**Issue by digoptical22** [Mainflux/mainflux-lite#1531]
hi guys, when i run make run at mainflux ui project root i get an error like this, and i can't register and login to the system, can someone tell me why??
this is log when i ran sudo make run
mainflux-users     | {"level":"info","message":"gRPC communication is not encrypted","ts":"2021-12-21T15:42:43.1549947Z"}
mainflux-users     | {"level":"error","message":"Failed to configure e-mailing util: Parse e-mail template failed : read email.tmpl: is a directory","ts":"2021-12-21T15:42:43.167394098Z"}
mainflux-users     | {"level":"error","message":"failed to create admin user: rpc error: code = Internal desc = internal server error","ts":"2021-12-21T15:42:43.17953984Z"}
mainflux-users exited with code 1
mainflux-twins-db  | {"t":{"$date":"2021-12-21T15:43:05.825+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1640101385:825398][1:0x7fe860fa2700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 54, snapshot max: 54 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0)"}}
mainflux-users     | {"level":"error","message":"Failed to configure e-mailing util: Parse e-mail template failed : read email.tmpl: is a directory","ts":"2021-12-21T15:43:43.977635797Z"}
mainflux-users     | {"level":"error","message":"failed to create admin user: rpc error: code = Internal desc = internal server error","ts":"2021-12-21T15:43:43.989494615Z"}
mainflux-users exited with code 1
mainflux-twins-db  | {"t":{"$date":"2021-12-21T15:44:05.831+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1640101445:831360][1:0x7fe860fa2700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 55, snapshot max: 55 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0)"}}

![image](https://user-images.githubusercontent.com/58322053/146958388-709c71f3-24f5-4535-9760-d736f380fe0a.png)

**Comment by drasko** [comment]
@digoptical22 you were told already [here](https://github.com/mainflux/mainflux/issues/1527#issuecomment-992255428) to rspect the issue template.

Please do not overload GitHub with issues, use Gitter for questions of this type. GitHUb issues are not the place for learning, they are reserved for real issues with the software.

**Comment by manuio** [comment]
@digoptical22 Use `http://localhost`. `http://localhost:3000` is for internal use only, and is not intended to be used by the end-user.

**Comment by digoptical22** [comment]
hi @manuio i try http://localhost, but it still not working, i can't create user!!!!
this is the log and picture i try
mainflux-twins-db  | {"t":{"$date":"2022-01-18T13:52:51.820+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1642513971:820464][1:0x7f0a68fda700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 12, snapshot max: 12 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0)"}}
mainflux-users     | {"level":"info","message":"gRPC communication is not encrypted","ts":"2022-01-18T13:52:59.976686288Z"}
mainflux-users     | {"level":"error","message":"Failed to configure e-mailing util: Parse e-mail template failed : read email.tmpl: is a directory","ts":"2022-01-18T13:52:59.979761806Z"}
mainflux-auth      | {"level":"warn","message":"Method add_policy took 31.035µs to complete with error: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: lookup mainflux-keto on 127.0.0.11:53: server misbehaving\".","ts":"2022-01-18T13:52:59.984449649Z"}
mainflux-users     | {"level":"error","message":"failed to create admin user: rpc error: code = Internal desc = internal server error","ts":"2022-01-18T13:52:59.987158387Z"}
![image](https://user-images.githubusercontent.com/58322053/149950320-c5ed0cc5-7a00-4eb9-acfd-0fa4ff21c564.png)

**Comment by manuio** [comment]
@digoptical22 The problem is that you are using latest auth and users docker images (`Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup mainflux-keto`) but with an outdated docker-compose from UI repo. From github.com/mainflux/ui pull the latest version and try again.
