### ISSUE TITLE
Consider using service healthcheck in Dockerfile

### ISSUE THREAD

**Issue by dborovcanin** [Mainflux/mainflux-lite#1543]
**ENHANCEMENT**
1. Describe the enhancement you are requesting. 
We should consider using internal health check endpoints for exposing in Dockerfile like it's mentioned [here](https://github.com/mainflux/mainflux/pull/1541#pullrequestreview-849020252).
2. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).
This is a should-have enhancemenet.

**Comment by dborovcanin** [comment]
The only problem I see is that we need an external HTTP client to use our HTTP API health check endpoint (like in [this example](https://docs.docker.com/engine/reference/builder/#healthcheck)) and we are using `scratch` as a base image. However, there is always an option to create a simple Go binary instead of using tools such as `curl`.

**Comment by blokovi** [comment]
What I found interesting is that official docker images on docker hub do NOT have healtcheks.
Here are the reasons: https://github.com/docker-library/faq#healthcheck

Also, healthchecks can be implemented in [docker-compose](https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck), instead of in docker images, so given these reasons it may be better to use it there instead of `Dockerfile`

**Comment by dborovcanin** [comment]
> What I found interesting is that official docker images on docker hub do NOT have healtcheks. Here are the reasons: https://github.com/docker-library/faq#healthcheck
> 
> Also, healthchecks can be implemented in [docker-compose](https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck), instead of in docker images, so given these reasons it may be better to use it there instead of `Dockerfile`

These reasons sound sane to me. That is, we leave health checking to the user, and provide an endpoint that can be used for that. If @mainflux/maintainers agree, I will close this one.

**Comment by dborovcanin** [comment]
Closing this one due to reasons @blokovi explained in the comment.
