### ISSUE TITLE
Fix Cobra usage commands and clean unnecessary struct types

### ISSUE THREAD

**Issue by fbugarski** [Mainflux/mainflux-lite#1551]
**ENHANCEMENT**
1. Describe the enhancement you are requesting. Enhancements include:
   - code refactor

2. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).
nice-to-have

Clean unnecessary struct types in the initialization of slices

For example:
https://github.com/mainflux/mainflux/blob/bcc8cf71191efc8af64e595d292a7ef9a416b0ae/cli/groups.go#L14
https://github.com/mainflux/mainflux/blob/bcc8cf71191efc8af64e595d292a7ef9a416b0ae/cli/bootstrap.go#L39

**Comment by manuio** [comment]
@fbugarski Can you develop please. Which struct types are unecessary?

**Comment by fbugarski** [comment]
u can remove cobra.Command it is unnecessary, only bracket stay (in grp example row 14,46 ...)

**Comment by drasko** [comment]
Maybe we can tackle this remark: https://github.com/mainflux/mainflux/pull/1537#discussion_r792993517 in the same PR

**Comment by drasko** [comment]
@fbugarski please change title and specify that this is Cobra (or CLI) related

**Comment by manuio** [comment]
Partialy resolved here: https://github.com/mainflux/mainflux/issues/1261
And here: https://github.com/mainflux/mainflux/issues/1263
