### ISSUE TITLE
Fallback comment "//+build !test" missing for "//go:build !test" for Go versions v.16.x

### ISSUE THREAD

**Issue by chombium** [Mainflux/mainflux-lite#1577]
**BUG REPORT**

1. What were you trying to achieve?
Build mainflux with `make build` or separate microservices with `go build .` .

3. What are the expected results?
The build process finishes successfully.

5. What are the received results?
```bash
 make
CGO_ENABLED=0 GOOS= GOARCH=amd64 GOARM= go build -mod=vendor -ldflags "-s -w -X 'github.com/mainflux/mainflux.BuildTime=2022-03-14_23:37:37' -X 'github.com/mainflux/mainflux.Version=0.12.1' -X 'github.com/mainflux/mainflux.Commit=f3ed852b36219278ab873cf7af4f1aaadca628b4'" -o build/mainflux-users cmd/users/main.go
cmd/users/main.go:35:2: //go:build comment without // +build comment
make: *** [Makefile:78: users] Error 1
```

```bash
cd <path_to_cloned_mainflux_repo>/cmd/users
 go build .
main.go:35:2: //go:build comment without // +build comment
```

6. What are the steps to reproduce the issue?
- clone the repo
- try do build Mainflux or one of its services with go version earlier that v17.0.0

7. In what environment did you encounter the issue?
```bash
go version
go version go1.16.15 linux/amd64
```

I've encountered this issue with `go 1.16.15`, but I wanted to see with which go version does the problem starts. I found out that the problem appears with `go v1.16` and disappears with `go v17.0`.

8. Additional information you deem important:

I've checked what the Go design proposals and I've found this [draft proposal](<https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md>). In this document it is specified that the new notation is as we have it in the master at the moment `//go:build <comment>`, `//go:build !test`. It is also specified that as a [transition](https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md#transition) that:
```
Go 1.(N−1) would prepare for the transition with minimal changes. In Go 1.(N−1):

- Builds will fail when a Go source file contains //go:build lines without // +build lines.
```

This is why I could not build with `go v1.16.15`. The fix to support `go v16.x` in our case is to simply add another `// +build !test` line right after each `// go:build !test` line. If we add the `// +build !test` line it will be used as fallback for the older versions. The changes of the go build tag were introduced in the code with the [MF-1308 PR](https://github.com/mainflux/mainflux/pull/1541).

The fix would be to add the following pair wherever we have the build tag:
```go
//go:build !test
//+build !test
```
I've done test adding the lines above in few files and I could build successfully with `go v16.x`.

@mainflux/contributors What do you think? Should I create a PR with a fix?

**Comment by drasko** [comment]
@chombium yes, please go ahead - we will support the latest Go version on the master.

**Comment by dborovcanin** [comment]
I think that simply setting the minimum Go version to 1.17, which implicitly solves this problem, is perfectly fine. In `go.mod` file we also use `1.17`, and I've been even using `go mod tidy -compat=1.17` command when updating dependencies. This will solve both #1578 and #1577. I see no real benefits of keeping compatibility with Go 1.16 or below.

**Comment by drasko** [comment]
Agreed with @dusanb94

**Comment by chombium** [comment]
@dusanb94 I agree completely with you. I was thinking to fix this for go v16.x as there is is the stable bugfix release for the latest and latest - 1 release version for the go language itself. If we say we always need the latest stable version its also good, but we need to adjust the docs accordingly.
