### ISSUE TITLE
Minimum Go version for building Mainfux

### ISSUE THREAD

**Issue by chombium** [Mainflux/mainflux-lite#1578]
I was reading the [dev guide on read the docs](https://mainflux.readthedocs.io/en/latest/dev-guide/#prerequisites) to update my development environment and I saw that the minimum Go version specified in the docs is `Go v1.13.3`. 

Just out of curiosity, I've downloaded that version and tried to build Mainflux.

I got the following error:

```bash
 make
CGO_ENABLED=0 GOOS= GOARCH=amd64 GOARM= go build -mod=vendor -ldflags "-s -w -X 'github.com/mainflux/mainflux.BuildTime=2022-03-15_00:14:46' -X 'github.com/mainflux/mainflux.Version=0.12.1' -X 'github.com/mainflux/mainflux.Commit=f3ed852b36219278ab873cf7af4f1aaadca628b4'" -o build/mainflux-users cmd/users/main.go
# golang.org/x/net/http2
vendor/golang.org/x/net/http2/transport.go:417:45: undefined: os.ErrDeadlineExceeded
make: *** [Makefile:78: users] Error 2
```

Than I've tried `Go v.14.15` and I got the same error.

Digging through the code of go I found the that [os, net: define and use os.ErrDeadlineExceeded](https://github.com/golang/go/commit/d422f54619b5b6e6301eaa3e9f22cfa7b65063c8) was commited on 25th of April 2020 and inlcuded in go1.15beta1 (released in go1.15 stable).

Than I tried building Mainflux with go1.15 and the build finished successfully. Hence the minimum go version should be `go v1.15` and not as stated in the [dev guide](https://mainflux.readthedocs.io/en/latest/dev-guide/#prerequisites) in read the docs `go v1.13.3` nor the [latest version](https://github.com/mainflux/docs/blob/master/docs/dev-guide.md#prerequisites) in the master of the docs repo `go v1.17.5`. Of course the #1577 issue would have to be fixed as well to cover the `go v16.x` versions.

@mainflux/contributors wdyt?

**Comment by chombium** [comment]
btw. It seems to me that the latest version of the docs repo is not published on read the docs.

**Comment by drasko** [comment]
Yes, we moved to [mainflux.io](https://docs.mainflux.io/)

**Comment by chombium** [comment]
@drasko thanks for the info

**Comment by manuio** [comment]
@chombium I'd update the version in all docs since we are frequently aligning with latest Go versions.

**Comment by dborovcanin** [comment]
Since we're not using [readthedocs](https://mainflux.readthedocs.io/en/latest/dev-guide/#prerequisites) anymore, but [mainflux.io](https://docs.mainflux.io/), and I think those are up to date. @chombium Can we close this one?
