### ISSUE TITLE
Influxdb Writer changes format of update-time to string

### ISSUE THREAD

**Issue by Hasan98-git** [Mainflux/mainflux-lite#1580]
**BUG REPORT**

1. What were you trying to achieve?
I am using influxdb to store telemetry data, and while sending update-time as float data type to mainflux mqtt-broker, I noticed that the influxdb-writer service converts the update-time's data type from float to string. The writer shouldn't convert the datatype of incoming data and keep it as it is.

3. What are the expected results?
I expect update-time to be a floating-point number.

4. What are the received results?
Update time is stored as a string.

5. What are the steps to reproduce the issue?
Run latest Docker composition, run InfluxDB Writer, provision and connect thing and channel, send message to any of adapters.

6. In what environment did you encounter the issue?
Latest Docker compose; tested with multiple systems.

7. Additional information you deem important:
N/A

**Comment by manuio** [comment]
Looks like the issue is here: https://github.com/mainflux/mainflux/blob/127044efad54ff8ed7072f3ef3a47bb650d3a01f/consumers/writers/influxdb/fields.go#L12 
@drasko @dusanb94 Why we are converting this field to string?

**Comment by dborovcanin** [comment]
@manuio `UpdateTime` used to be a tag, and tags are strings. We updated the schema design moving it to values, but we forgot to remove this type change.
