### ISSUE TITLE
Use JWK for signing authentication token

### ISSUE THREAD

**Issue by mteodor** [Mainflux/mainflux-lite#1587]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

Currently authentication tokens are simply being signed using a secret, tokens should be possible to sign using JWK, that would add to flexibility to chose between different algorithms for signing and it can make authorization tokens exchanged with other applications, with exchange of `JWK` issued authorization token can be verified in other applications.

4. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

must-have

**Comment by arvindh123** [comment]
@mteodor  There is similar proposal https://github.com/absmach/magistrala/issues/1672 ,

**Comment by dborovcanin** [comment]
Closing in favor of #1672.
