### ISSUE TITLE
OpenTracing is archived, and they are recommending to migrate to OpenTelemetry.

### ISSUE THREAD

**Issue by chaymankala** [Mainflux/mainflux-lite#1591]
I would like to suggest this and know if the migration is possible.
The Docs: https://opentelemetry.io/docs/migration/opentracing/

**ENHANCEMENT**
1. Enhancements include
   - code refactor
   - tooling

2. Importance of this enhancement: nice-to-have.

**Comment by SammyOina** [comment]
This relates to #1732 , @dborovcanin this one should probably be closed

**Comment by dborovcanin** [comment]
Closed by #1732.
