### ISSUE TITLE
Migration from 0.12 to 0.13 corrupts users access to things

### ISSUE THREAD

**Issue by mteodor** [Mainflux/mainflux-lite#1602]
**BUG REPORT**

1. What were you trying to achieve?

Upgrade 0.12 to 0.13

3. What are the expected results?

When upgrading from mainflux version 0.12 to 0.13 to have access to all the previously things

6. What are the received results?
User is not able to see previously created things

8. What are the steps to reproduce the issue?
in version 0.12 create some users and with created users create some things
then upgrade to 0.13 and try to access things
9. In what environment did you encounter the issue?

10. Additional information you deem important:

we need to add policy into keto to make it work properly
for each user and the thing it owns we have to update policy as following

```
curl -XPUT  http://localhost:4081/relation-tuples --data '{ "namespace":"members", "object":"thing_id", "relation":"read", "subject_id":"email@example.com"}'

curl -XPUT  http://localhost:4081/relation-tuples --data '{ "namespace":"members", "object":"thing_id", "relation":"write", "subject_id":"email@example.com"}'

curl -XPUT  http://localhost:4081/relation-tuples --data '{ "namespace":"members", "object":"thing_id", "relation":"delete", "subject_id":"email@example.com"}'

curl -XPUT  http://localhost:4081/relation-tuples --data '{ "namespace":"members", "object":"thing_id", "relation":"read", "subject_set":{"namespace":"members","object":"authorities","relation":"member"}}'

curl -XPUT  http://localhost:4081/relation-tuples --data '{ "namespace":"members", "object":"thing_id", "relation":"edit", "subject_set":{"namespace":"members","object":"authorities","relation":"member"}}'

curl -XPUT  http://localhost:4081/relation-tuples --data '{ "namespace":"members", "object":"thing_id", "relation":"delete", "subject_set":{"namespace":"members","object":"authorities","relation":"member"}}'
```

**Comment by dborovcanin** [comment]
Related to #1490.

**Comment by dborovcanin** [comment]
This issue is over 2y old and it's worth investing our time into it unless someone finds it absolutely necessary. In that case, we can reopen this ticket or create a new one, but I am closing this for now.
