### ISSUE TITLE
Env file contains an invalid value

### ISSUE THREAD

**Issue by zhang-chuanfeng** [Mainflux/mainflux-lite#1603]
**BUG REPORT**

Running `docker-compose -f docker-compose.yml up` failed.

1. What were you trying to achieve?
I'm trying to run Docker composition using `docker-compose -f docker-compose.yml up`.

2. What are the expected results?
I expect the composition to run successfully.

3. What are the received results?
Running `docker-compose -f docker-compose.yml up` failed.

<img width="396" alt="Snipaste_2022-05-09_11-47-30" src="https://user-images.githubusercontent.com/59160162/167337625-a99112ed-752b-454d-a3a4-f3203d34c24a.png">

<img width="648" alt="Snipaste_2022-05-09_11-48-10" src="https://user-images.githubusercontent.com/59160162/167337667-c787c1c1-67d4-4b3f-93bb-4e6d78c8091b.png">

should MF_AUTH_LOGIN_TOKEN_DURATION=10h

5. What are the steps to reproduce the issue?
Run `docker-compose -f docker-compose.yml up`.

6. In what environment did you encounter the issue?
ubuntu

8. Additional information you deem important:
N/A

**Comment by manuio** [comment]
@zhang-chuanfeng Can you send a PR with this fix please?

**Comment by dborovcanin** [comment]
@zhang-chuanfeng **Please** fill out the bug report template correctly. There is a reason template exists and it is hard for us to follow if you don't write all the steps down. I fixed it, but we're missing the details on the environment this bug occurs or any other details you find important.
