### ISSUE TITLE
关于mainflux

### ISSUE THREAD

**Issue by sparkok** [Mainflux/mainflux-lite#1608]
你也在用mainflux么?我也在基于mainflux做开发，国人用这个的好像不多，如果可能加个好友认识一下吧。微信 q6457977

**Comment by dborovcanin** [comment]
I am not sure I understand the point of this issue, but maybe the translation is wrong - I (or any of the Maifnlux maintainers) do not speak Chinese. If you want to provide Mainflux README in Chinese, feel free to do so and we'll be more than happy to add a link to it on the official repository. Other than that, I don't see the value of this issue. Please use English as the official project language.
