### ISSUE TITLE
Invalid handling of auth errors in Things service

### ISSUE THREAD

**Issue by fhaze** [Mainflux/mainflux-lite#1614]
**BUG REPORT**

1. What were you trying to achieve?
I wanted to make sure the policies mechanism added on `mainflux/0.13.0` didn't break anything on our project. So while checking the `Things Api` I could check some strange behavior when trying to fetch `Things` that doesn't exist or the `User` doesn't have access to them. My test was quite simple, I just created a random `User` and tried to fetch a `Thing ID` that doesn't exist.

3. What are the expected results?
`404 Not Found` same as `mainflux/0.12.1`

4. What are the received results?
`500 Internal Server Error`

5. What are the steps to reproduce the issue?
```sh
curl -s -X POST -H "Content-Type: application/json" http://localhost:8180/users -d '{"email":"hoge@mail.com","password":"12345678"}'
TOKEN=$(curl -s -X POST -H "Content-Type: application/json" http://localhost:8180/tokens -d '{"email":"hoge@mail.com","password":"12345678"}' | jq -r ".token")
curl -s -X GET -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" http://localhost:8182/things/123
```

6. In what environment did you encounter the issue?
`mainflux/0.13.0`

7. Additional information you deem important:
Same thing happens when I have a `Thing` but I don't have the `read` policies on `Keto` to access it. It also throws a `500 Internal Server Error` instead of `403 Forbidden` as the [documentation](https://docs.mainflux.io/authorization/) states.

**Comment by manuio** [comment]
@fhaze Looks like the migration issue between 0.12.0 and 0.13.0 explained here: https://github.com/mainflux/mainflux/issues/1602

**Comment by fhaze** [comment]
> @fhaze Looks like the migration issue between 0.12.0 and 0.13.0 explained here: #1602

The migration issue is another subject IMHO. I did my tests on a fresh `Mainflux/0.13.0` install (not an upgrade scenario).

**Comment by manuio** [comment]
In that case it's definitelly a bug. Can you delete the Thing? If not, you can probably use the fix from the issue. I remember to have a similar bug some days ago.

**Comment by fhaze** [comment]
Yeah, deleting a Thing works. The only problem I see is the wrong `500 Internal Server Error` response instead of `404 Not Found` when fething a nonexistent Thing. But thanks for the fast answer and fix. 😁

**Comment by manuio** [comment]
@fhaze This PR should fix your issue: https://github.com/mainflux/mainflux/pull/1615
