### ISSUE TITLE
Return all users with `mainflux-cli` command

### ISSUE THREAD

**Issue by zzokki81** [Mainflux/mainflux-lite#1618]
**BUG REPORT**

1. What were you trying to achieve?
When I log in as an administrator, I want the list of all users to be returned via the "mainflxs-cli" command

2. What are the expected results?
When login as admin all created users should be returned with:
`mainflux-cli users get <token>`

example:

`{
        "limit": 10,
        "offset": 0,
        "total": 5,
         "users": [
            {
                "email": "admin@example.com",
                "id": "c6fa0d9e-dc94-49c4-8d12-2613c81d5e0e"
            },
            {
              "email": "user@mail.com",
              "id": "0ed364ba-e887-4d5a-b1ad-6c68001528c7"
            },
          ...
      ]
}
`

3. What are the received results?
Empty object `{}`

4. What are the steps to reproduce the issue?
Login as admin and get all users with `mainflux-cli users get <token>`

5. In what environment did you encounter the issue?
`mainflux/0.13.0`

**Comment by rodneyosodo** [comment]
Hello @zzokki81 we are currently working on it this [PR](https://github.com/mainflux/mainflux/pull/1589)

**Comment by manuio** [comment]
@0x6f736f646f You can use this issue as reference for you PR

**Comment by manuio** [comment]
Resolved here: https://github.com/mainflux/mainflux/pull/1589
