### ISSUE TITLE
Questions about Provisioning Things in the documentation

### ISSUE THREAD

**Issue by VeddySama** [Mainflux/mainflux-lite#1626]
I have the following error when I post request for /things/bulk according to the documentation, how can I solve this
![image](https://user-images.githubusercontent.com/49411287/177272573-d55a3c25-e5e7-4d04-aeb3-0a6b84f79ed0.png)
mainflux version 0.13.0

**Comment by VeddySama** [comment]
Re-creating users and re-acquiring tokens are useless

**Comment by dborovcanin** [comment]
Can you send logs from the Things and Auth service?

**Comment by VeddySama** [comment]
![image](https://user-images.githubusercontent.com/49411287/177274263-43dffdbd-5c01-4aeb-8473-107e5ed9c7f7.png)

**Comment by VeddySama** [comment]
This is the first time I use mainflux and follow the documentation, there may be some places I don't understand properly

**Comment by VeddySama** [comment]
The problem of connecting the auth service in the things service
