### ISSUE TITLE
Function signature mismatches on sdk

### ISSUE THREAD

**Issue by mclcavalcante** [Mainflux/mainflux-lite#1627]
The function signature is mismatching SDK interface and function implementation, see below:

- on interface aims to **connected** things:
https://github.com/mainflux/mainflux/blob/931b48f3a7d6fffac3f53568bff19e9a59d31586/pkg/sdk/go/sdk.go#L167

- on implementation aims to **disconnected** things:
https://github.com/mainflux/mainflux/blob/931b48f3a7d6fffac3f53568bff19e9a59d31586/pkg/sdk/go/things.go#L128

In fact, the returning is for disconnected things https://github.com/mainflux/mainflux/blob/931b48f3a7d6fffac3f53568bff19e9a59d31586/pkg/sdk/go/things.go#L129
This is not a bug indeed, but it is really confusing at the first sign, and took me a few hours to realize this problem

**Comment by manuio** [comment]
@mclcavalcante Indeed, very confusing. We simply forgot to rename it after to change from `connected` to `disconnected`. But now we check the `disconnected` query parameter: https://github.com/mainflux/mainflux/blob/master/things/api/things/http/transport.go#L403 

Would you like to take this issue and fix it?

**Comment by mclcavalcante** [comment]
@manuio sure, I can do this, by the end of the day I'll open a PR
