### ISSUE TITLE
Create Postman collections for API documentation

### ISSUE THREAD

**Issue by drasko** [Mainflux/mainflux-lite#1644]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

Create Postman collections for API documentation.

4. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
Nice-to-have

**Comment by dborovcanin** [comment]
We'll use Openapi docs and examples that can be imported to Postman, as well, so we avoid duplicates and maintenance of both.
