### ISSUE TITLE
would you have plan to support automation  between things？

### ISSUE THREAD

**Issue by chenliuyang1989** [Mainflux/mainflux-lite#1652]
As title，Thanks.

**Comment by drasko** [comment]
What does that mean exactly?

**Comment by chenliuyang1989** [comment]
if some event happens then trigger other things to do someaction。 like automaction at homekit

**Comment by drasko** [comment]
Use dedicated app as a subscriber to a Mainflux (look at Writers for example) and implement your custom actions. All the rest is our of scope of Mainflux (which is only an IoT messaging system).
