### ISSUE TITLE
Canot write json message with different data type of same key json

### ISSUE THREAD

**Issue by ChiQuang98** [Mainflux/mainflux-lite#1653]
first time:

I using MQTT client to publish message: { "QUYNH":3 } to mainflux. When I query in influxdb 
![image](https://user-images.githubusercontent.com/35691187/186619457-10537e60-fca2-46a9-82ef-28be42855cf3.png)

it works fine.

But second time: I publish message { "QUYNH":"3" } or { "QUYNH":"text" }, nothing write to influxdb. Why mainflux convert all data type to string before write to influxdb to avoid that issue?

**Comment by drasko** [comment]
@arvindh123 ca you please take a look at this if this is a bug, or it can be closed.

**Comment by dborovcanin** [comment]
Mainflux does not convert any data to a string. If you want to use strings - you send strings and that's it. If fields don't exist, InfluxDB will create them for you, which happens the first time you send a message. For the next message - the field is created and the value type has been set, so it's not possible to store the value of the different type. You can create your own transformer to convert to strings if that's what you want, using Mainflux JSON Transformer as a reference.
