### ISSUE TITLE
How to run the app?

### ISSUE THREAD

**Issue by cursedgrape** [Mainflux/mainflux-lite#1657]
I'm trying to run the app on macos by doing the following:

    >>> docker-compose -f docker/docker-compose.yml up
    Starting mainflux-keto-db    ... done
    Starting mainflux-users-db   ... done
    Starting mainflux-things-db  ... done
    Starting mainflux-broker       ... done
    Starting mainflux-auth-redis   ... done
    Starting mainflux-auth-db      ... done
    Starting mainflux-vernemq      ... done
    Starting mainflux-es-redis     ... done
    Starting mainflux-jaeger       ... done
    Starting mainflux-keto         ... done
    Starting mainflux-keto-migrate ... done
    Starting mainflux-auth         ... done
    Starting mainflux-things       ... done
    Starting mainflux-users        ... done
    Starting mainflux-coap         ... done
    Starting mainflux-mqtt         ... done
    Starting mainflux-ws           ... done
    Starting mainflux-http         ... done
    Starting mainflux-nginx        ... done
    Attaching to mainflux-users-db, mainflux-things-db, mainflux-keto-db, mainflux-es-redis, mainflux-auth-redis, mainflux-broker, mainflux-auth-db, mainflux-vernemq, mainflux-jaeger, mainflux-keto-migrate, mainflux-keto, mainflux-auth, mainflux-things, mainflux-users, mainflux-mqtt, mainflux-coap, mainflux-http, mainflux-ws, mainflux-nginx
    mainflux-auth   | {"level":"info","message":"Authentication service started using http, exposed port 8189","ts":"2022-09-21T13:09:22.156499571Z"}
    mainflux-auth   | {"level":"info","message":"Authentication gRPC service started using http on port 8181","ts":"2022-09-21T13:09:22.160148792Z"}
    mainflux-auth   | {"level":"info","message":"Authentication gRPC service started, exposed port 8181","ts":"2022-09-21T13:09:22.160297725Z"}
    mainflux-auth   | {"level":"info","message":"Method authorize took 17.775019ms to complete without errors.","ts":"2022-09-21T13:09:23.32208128Z"}
    mainflux-auth   | {"level":"info","message":"Method authorize took 4.075057ms to complete without errors.","ts":"2022-09-21T13:09:23.328665082Z"}
    mainflux-auth-db | 
    mainflux-auth-db | PostgreSQL Database directory appears to contain a database; Skipping initialization
    mainflux-auth-db | 
    mainflux-auth-db | 2022-09-21 13:09:21.125 UTC [1] LOG:  starting PostgreSQL 13.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
    mainflux-auth-db | 2022-09-21 13:09:21.125 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
    mainflux-auth-db | 2022-09-21 13:09:21.125 UTC [1] LOG:  listening on IPv6 address "::", port 5432
    mainflux-auth-db | 2022-09-21 13:09:21.137 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
    mainflux-auth-db | 2022-09-21 13:09:21.146 UTC [21] LOG:  database system was shut down at 2022-09-21 13:07:55 UTC
    mainflux-auth-db | 2022-09-21 13:09:21.150 UTC [1] LOG:  database system is ready to accept connections
    mainflux-auth-redis | 1:C 21 Sep 2022 13:09:20.633 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
    mainflux-auth-redis | 1:C 21 Sep 2022 13:09:20.635 # Redis version=6.2.2, bits=64, commit=00000000, modified=0, pid=1, just started
    mainflux-auth-redis | 1:C 21 Sep 2022 13:09:20.635 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
    mainflux-auth-redis | 1:M 21 Sep 2022 13:09:20.644 * monotonic clock: POSIX clock_gettime
    mainflux-auth-redis | 1:M 21 Sep 2022 13:09:20.645 * Running mode=standalone, port=6379.
    mainflux-auth-redis | 1:M 21 Sep 2022 13:09:20.645 # Server initialized
    mainflux-auth-redis | 1:M 21 Sep 2022 13:09:20.645 * Loading RDB produced by version 6.2.2
    mainflux-auth-redis | 1:M 21 Sep 2022 13:09:20.645 * RDB age 97 seconds
    mainflux-auth-redis | 1:M 21 Sep 2022 13:09:20.645 * RDB memory usage when created 0.77 Mb
    mainflux-auth-redis | 1:M 21 Sep 2022 13:09:20.645 * DB loaded from disk: 0.000 seconds
    mainflux-auth-redis | 1:M 21 Sep 2022 13:09:20.645 * Ready to accept connections
    mainflux-broker | [1] 2022/09/21 13:09:20.812891 [INF] Starting nats-server
    mainflux-broker | [1] 2022/09/21 13:09:20.813047 [INF]   Version:  2.2.4
    mainflux-broker | [1] 2022/09/21 13:09:20.813052 [INF]   Git:      [924b314]
    mainflux-broker | [1] 2022/09/21 13:09:20.813054 [INF]   Name:     NBXZMZ4TY365YQVSOKDCL6NDKLS5J7ZLPWIEJOEA2MCJCYEPUC2VDVVD
    mainflux-broker | [1] 2022/09/21 13:09:20.813057 [INF]   ID:       NBXZMZ4TY365YQVSOKDCL6NDKLS5J7ZLPWIEJOEA2MCJCYEPUC2VDVVD
    mainflux-broker | [1] 2022/09/21 13:09:20.813064 [INF] Using configuration file: /etc/nats/nats.conf
    mainflux-es-redis | 1:C 21 Sep 2022 13:09:20.607 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
    mainflux-es-redis | 1:C 21 Sep 2022 13:09:20.607 # Redis version=6.2.2, bits=64, commit=00000000, modified=0, pid=1, just started
    mainflux-es-redis | 1:C 21 Sep 2022 13:09:20.607 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
    mainflux-es-redis | 1:M 21 Sep 2022 13:09:20.608 * monotonic clock: POSIX clock_gettime
    mainflux-es-redis | 1:M 21 Sep 2022 13:09:20.609 * Running mode=standalone, port=6379.
    mainflux-es-redis | 1:M 21 Sep 2022 13:09:20.609 # Server initialized
    mainflux-es-redis | 1:M 21 Sep 2022 13:09:20.613 * Loading RDB produced by version 6.2.2
    mainflux-es-redis | 1:M 21 Sep 2022 13:09:20.613 * RDB age 97 seconds
    mainflux-es-redis | 1:M 21 Sep 2022 13:09:20.613 * RDB memory usage when created 0.77 Mb
    mainflux-es-redis | 1:M 21 Sep 2022 13:09:20.613 * DB loaded from disk: 0.000 seconds
    mainflux-es-redis | 1:M 21 Sep 2022 13:09:20.613 * Ready to accept connections
    mainflux-coap   | 2022/09/21 13:09:24 The binary was build using Nats as the message broker
    mainflux-broker | [1] 2022/09/21 13:09:20.817767 [INF] Listening for client connections on 0.0.0.0:4222
    mainflux-broker | [1] 2022/09/21 13:09:20.818116 [INF] Server is ready
    mainflux-coap   | {"level":"info","message":"gRPC communication is not encrypted","ts":"2022-09-21T13:09:24.261363433Z"}
    mainflux-coap   | {"level":"info","message":"CoAP service started, exposed port 5683","ts":"2022-09-21T13:09:24.28230807Z"}
    mainflux-coap   | {"level":"info","message":"CoAP adapter service started, exposed port 5683","ts":"2022-09-21T13:09:24.282542337Z"}
    mainflux-http   | 2022/09/21 13:09:24 The binary was build using Nats as the message broker
    mainflux-http   | {"level":"info","message":"gRPC communication is not encrypted","ts":"2022-09-21T13:09:24.431035331Z"}
    mainflux-jaeger | 2022/09/21 13:09:21 maxprocs: Leaving GOMAXPROCS=2: CPU quota undefined
    mainflux-http   | {"level":"info","message":"HTTP adapter service started on port 8185","ts":"2022-09-21T13:09:24.439457003Z"}
    mainflux-nginx  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
    mainflux-nginx  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
    mainflux-jaeger | {"level":"info","ts":1663765761.222892,"caller":"flags/service.go:116","msg":"Mounting metrics handler on admin server","route":"/metrics"}
    mainflux-mqtt   | 2022/09/21 13:09:23 The binary was build using Nats as the message broker
    mainflux-keto-db | 
    mainflux-keto-db | PostgreSQL Database directory appears to contain a database; Skipping initialization
    mainflux-keto-db | 
    mainflux-keto-migrate | time=2022-09-21T13:09:21Z level=info msg=No tracer configured - skipping tracing setup audience=application service_name=ORY Keto service_version=master
    mainflux-mqtt   | {"level":"info","message":"Broker not ready: Get \"http://vernemq:8888/health\": dial tcp 172.18.0.9:8888: connect: connection refused, next try in 623.339213ms","ts":"2022-09-21T13:09:23.890542526Z"}
    mainflux-keto-migrate | Current status:
    mainflux-nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/entrypoint.sh
    mainflux-jaeger | {"level":"info","ts":1663765761.2235043,"caller":"flags/admin.go:120","msg":"Mounting health check on admin server","route":"/"}
    mainflux-keto-db | 2022-09-21 13:09:20.085 UTC [1] LOG:  starting PostgreSQL 13.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
    mainflux-things | {"level":"info","message":"gRPC communication is not encrypted","ts":"2022-09-21T13:09:22.899231489Z"}
    mainflux-mqtt   | {"level":"info","message":"Broker not ready: Get \"http://vernemq:8888/health\": dial tcp 172.18.0.9:8888: connect: connection refused, next try in 803.264071ms","ts":"2022-09-21T13:09:24.516856453Z"}
    mainflux-keto   | time=2022-09-21T13:09:21Z level=info msg=No tracer configured - skipping tracing setup audience=application service_name=ORY Keto service_version=master
    mainflux-keto   | time=2022-09-21T13:09:23Z level=info msg=finished unary call with code OK audience=application grpc.code=OK grpc.method=Check grpc.service=ory.keto.acl.v1alpha1.CheckService grpc.start_time=2022-09-21T13:09:23Z grpc.time_ms=15.908 service_name=ORY Keto service_version=master span.kind=server system=grpc
    mainflux-keto   | time=2022-09-21T13:09:23Z level=info msg=finished unary call with code OK audience=application grpc.code=OK grpc.method=Check grpc.service=ory.keto.acl.v1alpha1.CheckService grpc.start_time=2022-09-21T13:09:23Z grpc.time_ms=1.987 service_name=ORY Keto service_version=master span.kind=server system=grpc
    mainflux-keto-db | 2022-09-21 13:09:20.087 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
    mainflux-keto-db | 2022-09-21 13:09:20.088 UTC [1] LOG:  listening on IPv6 address "::", port 5432
    mainflux-keto-migrate | Version		Name		Status	
    mainflux-things | {"level":"info","message":"Things thing-http service started using http on port 8182","ts":"2022-09-21T13:09:22.948942006Z"}
    mainflux-things | {"level":"info","message":"Things auth-http service started using http on port 8182","ts":"2022-09-21T13:09:22.949733912Z"}
    mainflux-things | {"level":"info","message":"Things gRPC service started using http on port 8183","ts":"2022-09-21T13:09:22.94994274Z"}
    mainflux-keto-db | 2022-09-21 13:09:20.095 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
    mainflux-users  | {"level":"info","message":"gRPC communication is not encrypted","ts":"2022-09-21T13:09:23.243447712Z"}
    mainflux-things-db | 
    mainflux-things-db | PostgreSQL Database directory appears to contain a database; Skipping initialization
    mainflux-things-db | 
    mainflux-things-db | 2022-09-21 13:09:19.806 UTC [1] LOG:  starting PostgreSQL 13.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
    mainflux-things-db | 2022-09-21 13:09:19.806 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
    mainflux-things-db | 2022-09-21 13:09:19.806 UTC [1] LOG:  listening on IPv6 address "::", port 5432
    mainflux-jaeger | {"level":"info","ts":1663765761.2237158,"caller":"flags/admin.go:126","msg":"Starting admin HTTP server","http-addr":":14269"}
    mainflux-users  | {"level":"info","message":"Users service started using http, exposed port 8180","ts":"2022-09-21T13:09:23.330505765Z"}
    mainflux-things-db | 2022-09-21 13:09:19.811 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
    mainflux-jaeger | {"level":"info","ts":1663765761.2238517,"caller":"flags/admin.go:112","msg":"Admin server started","http.host-port":"[::]:14269","health-status":"unavailable"}
    mainflux-keto-db | 2022-09-21 13:09:20.101 UTC [21] LOG:  database system was shut down at 2022-09-21 13:07:56 UTC
    mainflux-ws     | 2022/09/21 13:09:24 The binary was build using Nats as the message broker
    mainflux-ws     | {"level":"info","message":"gRPC communication is not encrypted","ts":"2022-09-21T13:09:24.483131763Z"}
    mainflux-users-db | 
    mainflux-users-db | PostgreSQL Database directory appears to contain a database; Skipping initialization
    mainflux-users-db | 
    mainflux-users-db | 2022-09-21 13:09:19.488 UTC [1] LOG:  starting PostgreSQL 13.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
    mainflux-users-db | 2022-09-21 13:09:19.488 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
    mainflux-users-db | 2022-09-21 13:09:19.488 UTC [1] LOG:  listening on IPv6 address "::", port 5432
    mainflux-users-db | 2022-09-21 13:09:19.493 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
    mainflux-keto-db | 2022-09-21 13:09:20.108 UTC [1] LOG:  database system is ready to accept connections
    mainflux-things-db | 2022-09-21 13:09:19.816 UTC [21] LOG:  database system was shut down at 2022-09-21 13:07:55 UTC
    mainflux-users-db | 2022-09-21 13:09:19.497 UTC [21] LOG:  database system was shut down at 2022-09-21 13:07:54 UTC
    mainflux-users-db | 2022-09-21 13:09:19.500 UTC [1] LOG:  database system is ready to accept connections
    mainflux-jaeger | {"level":"info","ts":1663765761.2398903,"caller":"memory/factory.go:61","msg":"Memory storage initialized","configuration":{"MaxTraces":0}}
    mainflux-jaeger | {"level":"info","ts":1663765761.282721,"caller":"server/grpc.go:76","msg":"Starting jaeger-collector gRPC server","grpc.host-port":":14250"}
    mainflux-keto-migrate | 20201110175414	relationtuple	Applied	
    mainflux-keto-migrate | All migrations are already applied, there is nothing to do.
    mainflux-keto-migrate | 
    mainflux-keto-migrate | Going to migrate namespaces.
    mainflux-keto-migrate | [namespace=members] Current status:
    mainflux-ws     | {"level":"info","message":"WS adapter service started, exposed port 8190","ts":"2022-09-21T13:09:24.499328391Z"}
    mainflux-things-db | 2022-09-21 13:09:19.819 UTC [1] LOG:  database system is ready to accept connections
    mainflux-jaeger | {"level":"info","ts":1663765761.2874434,"caller":"server/http.go:44","msg":"Starting jaeger-collector HTTP server","http host-port":":14268"}
    mainflux-jaeger | {"level":"info","ts":1663765761.2884471,"caller":"server/zipkin.go:48","msg":"Listening for Zipkin HTTP traffic","zipkin host-port":":0"}
    mainflux-jaeger | {"level":"info","ts":1663765761.4094646,"caller":"grpc/builder.go:67","msg":"Agent requested insecure grpc connection to collector(s)"}
    mainflux-jaeger | {"level":"info","ts":1663765761.4099948,"caller":"grpc@v1.29.1/clientconn.go:243","msg":"parsed scheme: \"\"","system":"grpc","grpc_log":true}
    mainflux-jaeger | {"level":"info","ts":1663765761.4105372,"caller":"grpc@v1.29.1/clientconn.go:249","msg":"scheme \"\" not registered, fallback to default scheme","system":"grpc","grpc_log":true}
    mainflux-jaeger | {"level":"info","ts":1663765761.4111617,"caller":"grpc@v1.29.1/resolver_conn_wrapper.go:143","msg":"ccResolverWrapper: sending update to cc: {[{:14250  <nil> 0 <nil>}] <nil> <nil>}","system":"grpc","grpc_log":true}
    mainflux-jaeger | {"level":"info","ts":1663765761.4114091,"caller":"grpc@v1.29.1/clientconn.go:667","msg":"ClientConn switching balancer to \"round_robin\"","system":"grpc","grpc_log":true}
    mainflux-jaeger | {"level":"info","ts":1663765761.411953,"caller":"grpc@v1.29.1/clientconn.go:682","msg":"Channel switches to new LB policy \"round_robin\"","system":"grpc","grpc_log":true}
    mainflux-jaeger | {"level":"info","ts":1663765761.412379,"caller":"grpc@v1.29.1/clientconn.go:1056","msg":"Subchannel Connectivity change to CONNECTING","system":"grpc","grpc_log":true}
    mainflux-jaeger | {"level":"info","ts":1663765761.4130375,"caller":"grpc@v1.29.1/clientconn.go:417","msg":"Channel Connectivity change to CONNECTING","system":"grpc","grpc_log":true}
    mainflux-jaeger | {"level":"info","ts":1663765761.4137008,"caller":"grpc@v1.29.1/clientconn.go:1193","msg":"Subchannel picks a new address \":14250\" to connect","system":"grpc","grpc_log":true}
    mainflux-jaeger | {"level":"info","ts":1663765761.4149382,"caller":"grpc@v1.29.1/clientconn.go:1056","msg":"Subchannel Connectivity change to READY","system":"grpc","grpc_log":true}
    mainflux-jaeger | {"level":"info","ts":1663765761.415439,"caller":"base/balancer.go:200","msg":"roundrobinPicker: newPicker called with info: {map[0xc0004b3980:{{:14250  <nil> 0 <nil>}}]}","system":"grpc","grpc_log":true}
    mainflux-jaeger | {"level":"info","ts":1663765761.4158027,"caller":"grpc@v1.29.1/clientconn.go:417","msg":"Channel Connectivity change to READY","system":"grpc","grpc_log":true}
    mainflux-jaeger | {"level":"info","ts":1663765761.416582,"caller":"grpc/builder.go:101","msg":"Checking connection to collector"}
    mainflux-jaeger | {"level":"info","ts":1663765761.4166846,"caller":"grpc/builder.go:104","msg":"Agent collector connection state change","dialTarget":":14250","status":"READY"}
    mainflux-jaeger | {"level":"info","ts":1663765761.4184964,"caller":"command-line-arguments/main.go:212","msg":"Starting agent"}
    mainflux-jaeger | {"level":"info","ts":1663765761.4190624,"caller":"querysvc/query_service.go:137","msg":"Archive storage not created","reason":"archive storage not supported"}
    mainflux-jaeger | {"level":"info","ts":1663765761.4196975,"caller":"app/flags.go:143","msg":"Archive storage not initialized"}
    mainflux-jaeger | {"level":"info","ts":1663765761.419517,"caller":"app/agent.go:69","msg":"Starting jaeger-agent HTTP server","http-port":5778}
    mainflux-jaeger | {"level":"info","ts":1663765761.421452,"caller":"app/server.go:163","msg":"Query server started","port":16686,"addr":":16686"}
    mainflux-jaeger | {"level":"info","ts":1663765761.4215972,"caller":"healthcheck/handler.go:128","msg":"Health Check state change","status":"ready"}
    mainflux-jaeger | {"level":"info","ts":1663765761.421809,"caller":"app/server.go:208","msg":"Starting HTTP server","port":16686,"addr":":16686"}
    mainflux-jaeger | {"level":"info","ts":1663765761.4219506,"caller":"app/server.go:221","msg":"Starting GRPC server","port":16686,"addr":":16686"}
    mainflux-jaeger | {"level":"info","ts":1663765761.4224257,"caller":"app/server.go:232","msg":"Starting CMUX server","port":16686,"addr":":16686"}
    mainflux-keto-migrate | Version		Name		Status	
    mainflux-keto-migrate | 20210128140414	namespace	Applied	
    mainflux-keto-migrate | [namespace=members] All migrations are already applied, there is nothing to do.
    mainflux-keto-migrate exited with code 0
    mainflux-mqtt   | {"level":"info","message":"Broker not ready: Get \"http://vernemq:8888/health\": dial tcp 172.18.0.9:8888: connect: connection refused, next try in 1.440878299s","ts":"2022-09-21T13:09:25.322405173Z"}
    mainflux-mqtt   | {"level":"info","message":"Broker not ready: Get \"http://vernemq:8888/health\": dial tcp 172.18.0.9:8888: connect: connection refused, next try in 1.214015824s","ts":"2022-09-21T13:09:26.764858635Z"}
    mainflux-vernemq | config is OK
    mainflux-vernemq | -config /vernemq/data/generated.configs/app.2022.09.21.13.09.25.config -args_file /vernemq/bin/../etc/vm.args -vm_args /vernemq/bin/../etc/vm.args
    mainflux-vernemq | Exec:  /vernemq/bin/../erts-12.3.1/bin/erlexec -boot /vernemq/bin/../releases/1.12.5/vernemq               -config /vernemq/data/generated.configs/app.2022.09.21.13.09.25.config -args_file /vernemq/bin/../etc/vm.args -vm_args /vernemq/bin/../etc/vm.args              -pa /vernemq/bin/../lib/erlio-patches -- console -noshell -noinput
    mainflux-vernemq | Root: /vernemq/bin/..
    mainflux-vernemq | Loaded NodeClock fromDisk #{{'VerneMQ@172.18.0.10',
    mainflux-vernemq |                                 <<61,143,3,185,110,237,23,75,119,56,22,16,
    mainflux-vernemq |                                   157,72,48,129,178,147,133,32>>} =>
    mainflux-vernemq |                                 {0,0}}
    mainflux-vernemq | Loaded NodeClock fromDisk #{{'VerneMQ@172.18.0.10',
    mainflux-vernemq |                                 <<61,143,3,185,110,237,23,75,119,56,22,16,
    mainflux-vernemq |                                   157,72,48,129,178,147,133,32>>} =>
    mainflux-vernemq |                                 {0,0}}
    mainflux-vernemq | Loaded NodeClock fromDisk #{{'VerneMQ@172.18.0.10',
    mainflux-vernemq |                                 <<61,143,3,185,110,237,23,75,119,56,22,16,
    mainflux-vernemq |                                   157,72,48,129,178,147,133,32>>} =>
    mainflux-vernemq |                                 {0,0}}
    mainflux-vernemq | Loaded NodeClock fromDisk #{{'VerneMQ@172.18.0.10',
    mainflux-vernemq |                                 <<61,143,3,185,110,237,23,75,119,56,22,16,
    mainflux-vernemq |                                   157,72,48,129,178,147,133,32>>} =>
    mainflux-vernemq |                                 {0,0}}
    mainflux-vernemq | Loaded NodeClock fromDisk #{{'VerneMQ@172.18.0.10',
    mainflux-vernemq |                                 <<61,143,3,185,110,237,23,75,119,56,22,16,
    mainflux-vernemq |                                   157,72,48,129,178,147,133,32>>} =>
    mainflux-vernemq |                                 {0,0}}
    mainflux-vernemq | Loaded NodeClock fromDisk #{{'VerneMQ@172.18.0.10',
    mainflux-vernemq |                                 <<61,143,3,185,110,237,23,75,119,56,22,16,
    mainflux-vernemq |                                   157,72,48,129,178,147,133,32>>} =>
    mainflux-vernemq |                                 {2,0}}
    mainflux-vernemq | Loaded NodeClock fromDisk #{{'VerneMQ@172.18.0.10',
    mainflux-vernemq |                                 <<61,143,3,185,110,237,23,75,119,56,22,16,
    mainflux-vernemq |                                   157,72,48,129,178,147,133,32>>} =>
    mainflux-vernemq |                                 {0,0}}
    mainflux-vernemq | Loaded NodeClock fromDisk #{{'VerneMQ@172.18.0.10',
    mainflux-vernemq |                                 <<61,143,3,185,110,237,23,75,119,56,22,16,
    mainflux-vernemq |                                   157,72,48,129,178,147,133,32>>} =>
    mainflux-vernemq |                                 {0,0}}
    mainflux-vernemq | Loaded NodeClock fromDisk #{{'VerneMQ@172.18.0.10',
    mainflux-vernemq |                                 <<61,143,3,185,110,237,23,75,119,56,22,16,
    mainflux-vernemq |                                   157,72,48,129,178,147,133,32>>} =>
    mainflux-vernemq |                                 {0,0}}
    mainflux-mqtt   | {"level":"info","message":"Broker not ready: Get \"http://vernemq:8888/health\": dial tcp 172.18.0.9:8888: connect: connection refused, next try in 2.84707307s","ts":"2022-09-21T13:09:27.98107202Z"}
    mainflux-vernemq | Loaded NodeClock fromDisk #{{'VerneMQ@172.18.0.10',
    mainflux-vernemq |                                 <<61,143,3,185,110,237,23,75,119,56,22,16,
    mainflux-vernemq |                                   157,72,48,129,178,147,133,32>>} =>
    mainflux-vernemq |                                 {0,0}}
    mainflux-vernemq | 13:09:28.447 [error] can't reconfigure mqtts listener({127,0,0,1}, 1883) with Options [{max_connections,10000},{nr_of_acceptors,10},{mountpoint,[]},{depth,1},{eccs,[secp521r1,brainpoolP512r1,brainpoolP384r1,secp384r1,brainpoolP256r1,secp256k1,secp256r1,secp224k1,secp224r1,secp192k1,secp192r1,secp160k1,secp160r1,secp160r2]},{require_certificate,false},{tls_version,'tlsv1.2'},{use_identity_as_username,false},{allowed_protocol_versions,[3,4,131]},{allow_anonymous_override,false}] due to {already_started,<0.445.0>}
    mainflux-mqtt   | {"level":"info","message":"gRPC communication is not encrypted","ts":"2022-09-21T13:09:30.928775949Z"}
    mainflux-mqtt   | {"level":"info","message":"Starting MQTT proxy on port 1883","ts":"2022-09-21T13:09:30.987141604Z"}
    mainflux-mqtt   | {"level":"info","message":"Starting MQTT over WS  proxy on port 8080","ts":"2022-09-21T13:09:30.987220889Z"}
    mainflux-auth-db | 2022-09-21 13:14:21.407 UTC [26] LOG:  stats_timestamp 2022-09-21 13:14:21.413919+00 is later than collector's time 2022-09-21 13:14:21.407495+00 for database 13442

What should be done next?

**Comment by drasko** [comment]
Next step would be to go through the documentation: https://docs.mainflux.io/, especially "Getting STarted" chapter.
