### ISSUE TITLE
Postgres-reader error on http format?

### ISSUE THREAD

**Issue by kitty7c6** [Mainflux/mainflux-lite#1660]
**BUG REPORT**
1. What were you trying to achieve?
try to get data from postresql by Postgres-reader and command:
`curl -s -S -i  -H "Authorization: Thing <thing_key>" http://localhost:<service_port>/channels/<channel_id>/messages?offset=0&limit=5&format=<subtopic>`

my command:
`curl -s -S -i  -H "Authorization: Thing c2e49a79-61e7-41b5-91fc-285a3544560f" http://localhost:9204/channels/6efe11fe-c085-4c54-be2c-d7f2efcce74b/messages?offset=3&limit=2`

2. What are the expected results?

I expected to get 2 messages with offset 3

3. What are the received results?

`...  {"offset":3,"limit":10,"format":"messages","total":238,"messages":  ... `
limit is 10

and
 `[1]   Done                    curl -s -S -i -H "Authorization: Thing c2e49a79-61e7-41b5-91fc-285a3544560f" http://localhost:9204/channels/6efe11fe-c085-4c54-be2c-d7f2efcce74b/messages?offset=3`

4. What are the steps to reproduce the issue?
5. In what environment did you encounter the issue?
 Try this command with postresql 14, mainflux - master (git), debian 11.5

7. Additional information you deem important:

I try few command variations and only the first parameter after `messages?` is always taken into account

`curl -s -S -i  -H "Authorization: Thing c2e49a79-61e7-41b5-91fc-285a3544560f" http://localhost:9204/channels/6efe11fe-c085-4c54-be2c-d7f2efcce74b/messages?limit=2&offset=3`

`{"offset":0,"limit":2,"format":"messages",`  and 
`[2]+  Done                    curl -s -S -i -H "Authorization: Thing c2e49a79-61e7-41b5-91fc-285a3544560f" http://localhost:9204/channels/6efe11fe-c085-4c54-be2c-d7f2efcce74b/messages?limit=2`

**Comment by manuio** [comment]
@kitty7c6 It's working properly for me. Which tags are you using? I don't see why it would change but can you try with postgres 13.3?

**Comment by kitty7c6** [comment]
@manuio Mainflux from master branch (already with ws-adapter), sql (PostgreSQL) 14.5 (Debian 14.5-1.pgdg110+1)

with postgresql 13 (find quickly psql (PostgreSQL) 13.8 (Debian 13.8-1.pgdg110+1)) - same.

How it looks if I use all parameters (offset, limit and format)
```
napster@salmon:~$ curl -s -S -i  -H "Authorization: Thing c2e49a79-61e7-41b5-91fc-285a3544560f" http://localhost:9204/channels/6efe11fe-c085-4c54-be2c-d7f2efcce74b/messages?offset=2&limit=3&format=qwerty
[1] 72356
[2] 72357
napster@salmon:~$ HTTP/1.1 200 OK
Content-Type: application/json
Date: Fri, 30 Sep 2022 04:41:57 GMT
Content-Length: 2029

{"offset":2,"limit":10,"format":"messages","total":238,"messages":[{"channel":"6efe11fe-c085-4c54-be2c-d7f2efcce74b","publisher":"31f50798-c4a7-4662-afec-2a303a12500f","protocol":"mqtt","name":"device_nametemperature","unit":"Cel","time":1664434387,"value":23.5},{"channel":"6efe11fe-c085-4c54-be2c-d7f2efcce74b","publisher":"31f50798-c4a7-4662-afec-2a303a12500f","protocol":"mqtt","name":"device_nametemperature","unit":"Cel","time":1664434387,"value":23.5},{"channel":"6efe11fe-c085-4c54-be2c-d7f2efcce74b","publisher":"31f50798-c4a7-4662-afec-2a303a12500f","protocol":"mqtt","name":"device_nametemperature","unit":"Cel","time":1664434387,"value":23.5},{"channel":"6efe11fe-c085-4c54-be2c-d7f2efcce74b","publisher":"31f50798-c4a7-4662-afec-2a303a12500f","protocol":"mqtt","name":"device_nametemperature","unit":"Cel","time":1664434387,"value":23.5},{"channel":"6efe11fe-c085-4c54-be2c-d7f2efcce74b","publisher":"31f50798-c4a7-4662-afec-2a303a12500f","protocol":"mqtt","name":"device_nametemperature","unit":"Cel","time":1664434387,"value":23.5},{"channel":"6efe11fe-c085-4c54-be2c-d7f2efcce74b","publisher":"31f50798-c4a7-4662-afec-2a303a12500f","protocol":"mqtt","name":"device_nametemperature","unit":"Cel","time":1664434387,"value":23.5},{"channel":"6efe11fe-c085-4c54-be2c-d7f2efcce74b","publisher":"31f50798-c4a7-4662-afec-2a303a12500f","protocol":"mqtt","name":"device_nametemperature","unit":"Cel","time":1664434387,"value":23.5},{"channel":"6efe11fe-c085-4c54-be2c-d7f2efcce74b","publisher":"31f50798-c4a7-4662-afec-2a303a12500f","protocol":"mqtt","name":"device_nametemperature","unit":"Cel","time":1664434387,"value":23.5},{"channel":"6efe11fe-c085-4c54-be2c-d7f2efcce74b","publisher":"31f50798-c4a7-4662-afec-2a303a12500f","protocol":"mqtt","name":"device_nametemperature","unit":"Cel","time":1664434387,"value":23.5},{"channel":"6efe11fe-c085-4c54-be2c-d7f2efcce74b","publisher":"31f50798-c4a7-4662-afec-2a303a12500f","protocol":"mqtt","name":"device_nametemperature","unit":"Cel","time":1664434387,"value":23.5}]}

[1]-  Done                    curl -s -S -i -H "Authorization: Thing c2e49a79-61e7-41b5-91fc-285a3544560f" http://localhost:9204/channels/6efe11fe-c085-4c54-be2c-d7f2efcce74b/messages?offset=2
[2]+  Done                    limit=3
```
info from mainflux terminal. 
![image](https://user-images.githubusercontent.com/111865617/193192927-5a10e8ff-4504-4938-9eb2-1ebf97e741ab.png)
If I understand right `with query {2 10       0   false   0   0 messages}`  = only the first param is recognized, others takes as default

How I can access to database from PostgreSQL (not from reader) or where it is/how it names?

upd1. find in .env name/uesr/pass/ = mainflux, but still can't find it in postgresql (here only postgres superuser and postgres_db + template0/1)
when I try to force connect to the user, I see in the postgresql.log `2022-09-30 00:29:00.389 AKDT [13250] mainflux@mainflux DETAIL:  Role "mainflux" does not exist.`

My be I did something wrong?
1. I got working mainflux. Than stoped mainflux, add to docker/docker-compose.yml needed data from docker/addons/postgres-writer/docker-compose.yml (and from reader too). 
2. Install postgreSQL 14 (late change to 13.8)
3. make run mainflux. 
4. Write from device to chanel, read it by postres-reader (and find that only first parameter is used). I can get history of all messages by postres-reader.
5. After it I try to see messages directly in postgresql and there is no user mainflux (or db)

upd2. Managed to enter to postrgesql. I didn't understand that needs to enter to docker container with postrges.
For others unthinking like me, use: `docker exec -it <postgres_name_container> psql -U <user_name>` from Os with mainflux 
 `$ sudo docker exec -it mainflux-postgres psql -U mainflux`  - works for me

But first error still exists.

upd3. Command via postgresql ` mainflux=# SELECT * FROM messages ORDER BY messages.time DESC LIMIT 2 OFFSET 4;`  - works
`

**Comment by drasko** [comment]
Closed due to inactivity
