### ISSUE TITLE
Error users migration

### ISSUE THREAD

**Issue by kevin27770** [Mainflux/mainflux-lite#1661]
**BUG REPORT**

1. What were you trying to achieve?
       Deploy core mainflux services

2. What are the expected results?
      Deploy all services successfully

3. What are the received results?
```
mainflux-users       | {"level":"error","message":"Failed to connect to postgres: Unable to create migration plan because of users_5: unknown migration in database","ts":"2022-10-21T12:21:30.123731652Z"}
```

4. What are the steps to reproduce the issue?
     Run `make run ` command

5. In what environment did you encounter the issue?
     Linux

6. Additional information you deem important:

**Comment by drasko** [comment]
@0x6f736f646f is this a bug, or should it be closed?

**Comment by arvindh123** [comment]
@kevin27770 , 
Could try to remove all the docker container , images and volumes with command ```docker-compose -f ./docker/docker-compose.yml down --rmi all -v ```  and after this try to start with ```make run```

**Comment by rodneyosodo** [comment]
> @0x6f736f646f is this a bug, or should it be closed?

I haven't encountered it

@kevin27770 could you provide steps on how you encountered this error?

**Comment by arvindh123** [comment]
@0x6f736f646f 
**To replicate the issue** 
Running Mainflux latest version with db in docker or standalone , 
Then downgrade the Mainflux version to v0.12 without clearing the users service DB in docker volume or standalone Postgres database ,

**The problem in the issue** 
If we use the same latest mainflux users docker db volume or standalone postgres database
in downgrade version like v0.12, In v0.12 there is no user_5 migrations, So migrate library throw error if there is any unknown migration in database.

**Fix**
To Ignore unknown migration add the line ```migrate.SetIgnoreUnknown(true)``` at https://github.com/mainflux/mainflux/blob/master/users/postgres/init.go#L91 will solve the error in issue

**Comment by dborovcanin** [comment]
Also, modifying the migrations table manually (just so you add the mentioned migration) would help. None of these is a good idea but looks like something went wrong with your upgrade flow, so I'm afraid manual intervention is needed.

**Comment by arvindh123** [comment]
> Also, modifying the migrations table manually (just so you add the mentioned migration) would help. None of these is a good idea but looks like something went wrong with your upgrade flow, so I'm afraid manual intervention is needed.


@dborovcanin I agree with your statement.

**Comment by dborovcanin** [comment]
I am closing this one due to inactivity. @kevin27770 Feel free to reopen if you have any updates you find essential.
