### ISSUE TITLE
Bug related to MQTT Adapter

### ISSUE THREAD

**Issue by ChiQuang98** [Mainflux/mainflux-lite#1673]
Hi
I recently tested the performance of the MQTT Adapter by Jmeter I get 10% errors.  Here is the log of the MQTT Adapter:
![image](https://user-images.githubusercontent.com/35691187/203468716-3f6fc2d5-3d2f-4b07-b37f-635590cc997b.png)
![image](https://user-images.githubusercontent.com/35691187/203468734-cbef41e3-0071-4922-b64d-a936a36b3e00.png)
80% of the message is transferred to VerneMQ successfully. 
![image](https://user-images.githubusercontent.com/35691187/203468813-7603a5b9-5f97-482f-892e-24486d47364e.png)

Any idea about this bug?

**Comment by chombium** [comment]
Hi @ChiQuang98,

It's hard to analyze the problem if you simply write that there is 10% message loss. From the screenshots of the logs it seems that something is not scaled properly for the given message load.

Could you please clarify the following:
- How did you do the tests? What was your load test procedure?
- How did you deploy Mainflux?
- What were the resources(CPU and memory) given to the services?
- What was the load, the number of the mqtt messages when you've seen the message drops?

If you give us some more details we could try to reproduce this possible problem.

Best Regards,
Jovan

**Comment by dborovcanin** [comment]
@ChiQuang98 Can you, please, provide some context and more info on this one? 
How did you test it? What was the environment and version of tools/Mainflux? Did you try it locally with the testing suite and Mainflux running on the same machine? What was the message size? How did you count messages? What's the QoS used? Please write down all the things that you deem important.
Also, 10% errors and 80% success do not add up to 100%.

**Comment by dborovcanin** [comment]
I am closing this one due to inactivity. @ChiQuang98 If you can provide a more detailed explanation and give us context, please feel free to reopen it, and we'll look into it.
