### ISSUE TITLE
Is mainflux support connect to Redis Sentinel

### ISSUE THREAD

**Issue by ChiQuang98** [Mainflux/mainflux-lite#1675]
I wonder whether mainflux support connects to Redis sentinal?

**Comment by drasko** [comment]
What is Redis sentinal?

**Comment by dborovcanin** [comment]
Mainflux uses Redis for event streaming, and we use the official Go client. What kind of Redis deployment (cluster, sentinel, single-instance) is up to you. If you want to use Redis as a key-value storage, you can implement a [Writer](https://github.com/mainflux/mainflux/tree/master/consumers) consumer for Redis.
