### ISSUE TITLE
Upgrade from 0.12.1 to 0.13.0 (latest version) causes error in user deployment

### ISSUE THREAD

**Issue by TuanNguyen2807** [Mainflux/mainflux-lite#1684]
Hi, I'm building an application on top of Mainflux, and I'm using docker and k8s for deployment. All services in use now are in v0.12.1, my db is PostgreSQL12, and it runs smoothly without throwing any error.

However, I'm trying to upgrade Mainflux version to 0.13.0, by changing configs in k8s to pull Mainflux latest version (0.13.0). All of my services still running, except user deployment. 

![image](https://user-images.githubusercontent.com/79234967/208610273-29c3e54a-bee1-455a-a9ee-de642feb9b1f.png)

When checking source code, I found that in ~/cmd/users/main.go, func **createAdmin** was add new parameter **auth**
![image](https://user-images.githubusercontent.com/79234967/208610435-9c3a0178-406b-48b5-85b0-baa5ba315b3d.png)

I also changed docker config deployment, followed the config in ~/docker/.env, but it's not worth. If I used the same config for deploying v0.12.1, everything would be fine, included user deployment module.  

Was that the main reason causing my error?

**Comment by AryanGodara** [comment]
Hi @TuanNguyen2807 , user-deployment is working for us.
I just updated to latest version, and created and ran all the services.
users is working for me, and I'm also able to work with both admin and regular users through the API.

Is it possible you didn't build the latest version of the services?

**Comment by dborovcanin** [comment]
Hello, @TuanNguyen2807. We are restructuring access control for 0.14 and 1.0, so if there is no absolute need to switch to 0.13, you can wait a couple more weeks for 0.14 and switch directly to it. It should be a simpler and easier transition than 0.12 to 0.13.

**Comment by TuanNguyen2807** [comment]
Yeah, thank you so much! I have another question. Is there anyway to connect things from one user to channels of another user?

**Comment by dborovcanin** [comment]
With 0.14 (we shifted approach and delayed 0.14 so we can re-implement our access control) changes that are going to be introduced soon, this issue being inactive for a while, and version still sub 1.0, we will not support this type of migrations out of the box just yet, since we are still focused on adding new features and improving the platform. That being said, creating migration tools would be a welcomed contribution and something we have on our roadmap, but it's not our priority yet.
