### ISSUE TITLE
 Move database abstract of all service to common package

### ISSUE THREAD

**Issue by arvindh123** [Mainflux/mainflux-lite#1689]
**ENHANCEMENT**
1. Describe the enhancement you are requesting. Enhancements include:
   - tests
   - code refactor 
      Database abstract are same for all service, so it will be better if we move them to common package, This improves code reusability 
   -  documentation
   - research
   - tooling

2. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).
    must-have

**Comment by WashingtonKK** [comment]
@arvindh123 and @dborovcanin should we proceed with this?

**Comment by dborovcanin** [comment]
@WashingtonKK Let's not proceed with this, it has been resolved by refactoring `internal` and grouping DB abstractions.
