### ISSUE TITLE
Environment variables name consistency 

### ISSUE THREAD

**Issue by arvindh123** [Mainflux/mainflux-lite#1690]
**ENHANCEMENT**
1. Describe the enhancement you are requesting. Enhancements include:
   - tests
   - code refactor
       Environment variables are not consistent in all service `main.go` , The consistent naming of environment variable will help use to maintain and load environment variables by common function and also help in elimination code  reptation
   - documentation
   - research
   - tooling

2. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).
    must-have

**Comment by dborovcanin** [comment]
This is a quick consistency check and we can close it since most of the work is already done with the introduction of new env var handling.

**Comment by nyagamunene** [comment]
All environmental variables checkout and are consistent with how we name them. We can close this issue.
