### ISSUE TITLE
Missing client_id argument in mTLS documentation

### ISSUE THREAD

**Issue by dulataldazharov** [Mainflux/mainflux-lite#1702]
**ENHANCEMENT**
1. Describe the enhancement you are requesting.

In the documentation for mTLS: https://docs.mainflux.io/authentication/#mutual-tls-authentication-with-x509-certificates
I believe in the mosquitto_sub/pub commands in the end, the argument for client_id is missing.
```console
mosquitto_pub -u <thing_id> -P <thing_key> ...
```
should be
```console
mosquitto_pub -i <thing_name> -u <thing_id> -P <thing_key> ...
```

3. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).
If this is indeed a mistake, please, fix it. It can give people a really hard time.

**Comment by drasko** [comment]
Can you please send a PR for this?

**Comment by dulataldazharov** [comment]
Created a PR in the docs repo: https://github.com/mainflux/docs/pull/135
Should've created the issue in docs in the first place.
Closing the issue, since it should probably belong under the docs repo.
