### ISSUE TITLE
Jaeger service consume too much memory

### ISSUE THREAD

**Issue by ChiQuang98** [Mainflux/mainflux-lite#1726]
I don't know why Jaeger service consumes too much memory.
![image](https://user-images.githubusercontent.com/35691187/219537093-0fa0652c-82e7-4e31-ba61-ee070d911f7f.png)
Any solution for this case, the rest of services mainflux is stable. btw, could I run mainflux in k8s without Jaeger service?

**Comment by dborovcanin** [comment]
I think this is a question for the Jaeger team.
With the current version of the master, Mainflux will work without Jaeger deployed, but you will see some errors that do not affect Mainflux functionality (except for tracing). If you open an issue to the Jaeger team, please link it here. And please follow the issue template in the future.
