### ISSUE TITLE
MQTT client_id not found

### ISSUE THREAD

**Issue by birdboxuser** [Mainflux/mainflux-lite#1743]
Help needed:

I am not sure what I am doing wrong:

Context:
- I created a user
- created 2 things & a channel
- Connected the channel & things.
- running docker-compose of v0.13.0 mainflux

Trying to subscribe or publish to the channel by being a thing but facing this error:
```sh
mosquitto_sub -u "7976e1d8-83e4-4766-a0e9-c60facc37481" -P "$THINGTOKEN" -t channels/13943e83-d05c-416d-930c-d0013afdedc5/messages -h localhost
```
```sh
beyond@homepc:~$ mosquitto_pub -u "6c45f816-90bb-4970-8a1a-6c26b3dc762b" -P "d35b6677-36fb-4e8d-8bb6-f2262df55161" -t channels/13943e83-d05c-416d-930c-d0013afdedc5/messages -m "test"
Error: The connection was lost.

``` 

```sh
mainflux-mqtt          | {"level":"info","message":"Accepted new client","ts":"2023-03-12T15:35:34.967389653Z"}
mainflux-mqtt          | {"level":"error","message":"disconnected client_id  and username 7976e1d8-83e4-4766-a0e9-c60facc37481","ts":"2023-03-12T15:35:34.969024537Z"}
mainflux-mqtt          | {"level":"warn","message":"Broken connection for client:  with error: failed proxying from MQTT broker to MQTT clientclient_id not found","ts":"2023-03-12T15:35:34.969609152Z"}
```

**Comment by SammyOina** [comment]
Hi, this is an error that occurs when the client id is not set, `-i <some client id>`. Please add this to mosquitto_pub or mosquitto_sub. 
The command should look a bit like this 
```
mosquitto_pub -u <thing_id> -P <thing_key> -t channels/<channel_id>/messages -h localhost -m '[{"bn":"some-base-name:","bt":1.276020076001e+09, "bu":"A","bver":5, "n":"voltage","u":"V","v":120.1}, {"n":"current","t":-5,"v":1.2}, {"n":"current","t":-4,"v":1.3}]' -i <some_client_id>

mosquitto_sub -u <thing_id> -P <thing_key> -t channels/<channel_id>/messages -h localhost -i <some_client_id>
```
There is currently a pull request to update the documentation to reflect this https://github.com/mainflux/docs/pull/135

**Comment by dborovcanin** [comment]
@birdboxuser As you can see from the logs, the client ID is not found. We'll update docs soon, but I'll close this PR since setting the client ID is supposed to solve your problem. If the issue persists once you set the client ID, please reopen this ticket.
