### ISSUE TITLE
Improve path parameters naming

### ISSUE THREAD

**Issue by dborovcanin** [Mainflux/mainflux-lite#1761]
**ENHANCEMENT**
1. Describe the enhancement you are requesting. Enhancements include:
 Improve path params naming. For example, endpoints in form of  `"/channels/:id/things"` are not self-explanatory as inexperienced developers might not be sure what the `id` represents - Thing ID or Channel ID. It should be updated to `"/channels/:chanId/things"`.

2. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).
This is a should-have.

**Comment by dhanusaputra** [comment]
hi, can i help with this please, thanks

**Comment by dborovcanin** [comment]
Hello, @dhanusaputra This ticket will be taken by @ianmuchyri, but feel free to check for other issues labeled as `good-first-issue`.
