### ISSUE TITLE
Incorrect CoAP POST request response status code

### ISSUE THREAD

**Issue by Giorgi-Totladze** [Mainflux/mainflux-lite#1787]
coap-client -e "[{"bn":"urn:dev:12345","bt":0,"bu":"s"},{"u":"lon","t":10,"v":16.751767},{"u":"lat","t":10,"v":61.215833},{"u":"%EL","t":10,"v":100},{"t":20,"v":100},{"t":37,"v":100},{"t":54,"v":100},{"t":71,"v":100},{"t":88,"v":100}]" -m post -v 7 'coap://example.com/channels/example-channel-id/messages?auth=example-thing-key

We are trying to send a CoAP POST request to our Mainflux COAP adapter which is behind the network load balancer (aws), unfortunately the client does not get a success response code from the Adapter, for example 2.01, but at the same time our NATS consumer successfully gets a message which is sent by the client. 

We are sending the message with "libcoap (https://github.com/obgm/libcoap)".

**Comment by dborovcanin** [comment]
@Giorgi-Totladze Can you send CoAP adapter logs, response code, and fill out bug issue template correctly?

**Comment by dborovcanin** [comment]
@Giorgi-Totladze I can confirm the bug, the status code we send is `2.05` - Content.

**Comment by Giorgi-Totladze** [comment]
> Can you send CoAP adapter logs, response code, and fill out bug issue template correctly?

Hello, as I see you already created a pull request and linked with the issue, do you still need CoAP adapter logs, response code, and to fill out bug issue template correctly?

**Comment by dborovcanin** [comment]
No need, this is a bug. In the future, please try to fill out the bug template since all the questions I have asked in the thread are already in the template and the goal of the template is to streamline the process.

**Comment by Giorgi-Totladze** [comment]
@dborovcanin Hello, when is the estimated time for this fix to be available on production?

**Comment by dborovcanin** [comment]
It is ready, we're waiting for @drasko's review.
