### ISSUE TITLE
Create mainflux entities in bulk mode

### ISSUE THREAD

**Issue by kozjax** [Mainflux/mainflux-lite#1809]
is it possible to create mainflux entities in bulk mode? I mean let say I want to create a thing, channel for it and twin for it - can I do it with one request? like in one transaction?

**Comment by SammyOina** [comment]
this possible to some extent using the provision service, see it here https://github.com/mainflux/mainflux/tree/master/provision

**Comment by dborovcanin** [comment]
It is not possible to do it in a "one transaction" though, since this is distributed system and ACID across MF services is not supported. Please try what @SammyOina suggested and reopen a ticket adding more details to your request if that doesn't work for you.
