### ISSUE TITLE
Migrate from OpenTracing to OpenTelemetry

### ISSUE THREAD

**Issue by luuvt** [Mainflux/mainflux-lite#1813]
I have a question: currently, lib jaeger-client-go is DEPRECATED! and move to OpenTelemetry SDK. Does the team have a plan to migrate jaeger-client-go to OpenTelemetry?
https://github.com/jaegertracing/jaeger-client-go

**Comment by drasko** [comment]
I think this is already done on the master. @dborovcanin and @SammyOina can confirm and tell the status.

**Comment by SammyOina** [comment]
[master](https://github.com/mainflux/mainflux/tree/master) still uses opentracing, but on [clients - 0.14](https://github.com/mainflux/mainflux/tree/clients) we have opentelemetry

**Comment by dborovcanin** [comment]
@SammyOina That's correct. I will not close this issue but I will address it in [this PR](https://github.com/mainflux/mainflux/pull/1716).

**Comment by luuvt** [comment]
Thanks, for the feedback from the Team 👍
