### ISSUE TITLE
Adding thing to group fails

### ISSUE THREAD

**Issue by revozhang** [Mainflux/mainflux-lite#1823]
**BUG REPORT**
I am testing group and policy functions in latest master branch and found out adding things to group fails. log says:
~~~
mainflux-users-db      | 2023-06-17 22:13:24.972 UTC [56] ERROR:  insert or update on table "policies" violates foreign key constraint "policies_subject_fkey"
mainflux-users-db      | 2023-06-17 22:13:24.972 UTC [56] DETAIL:  Key (subject)=(3745b6b0-1e7b-4571-8361-2748d109ed8b) is not present in table "clients".
~~~
which makes sense. Since you won't find thing ID in users DB. I don't believe this is intended design since in the docs it says /policies API interface you can assign user, thing or channel to a group:
~~~
Assign[#](https://docs.mainflux.io/api/#assign)
Assign user, thing or channel to a group

Must-have: user_token, group_id, member_id and member_action

curl -s -S -i -X POST -H "Content-Type: application/json" -H "Authorization: Bearer <user_token>" http://localhost/policies -d '{"subject": "<user_id>" | "<thing_id_>" | "<channel_id_>", "object": "<group_id>", "actions":["<client_actions>" | "<group_actions>"]}'
For example:
...
~~~

**Comment by dborovcanin** [comment]
Hello, @revozhang. It is correct, we need to update the documentation. However, it is the intended design. We wanted to keep users' group only for users, while Things groups can have external members. This effectively means that you can share thing with users (by adding them to a thing group), but you can only add a user to the users' group.

**Comment by revozhang** [comment]
Thank you @dborovcanin for your reply. I am trying to group Things but there is no Groups api in things service, only Channels api, which is implemented using the same group concept. Are you saying that channels will be the group for things and external IDs? Also I was able to create channel using admin and changed the policy of that channel to be able to g_list by a general user. The call to the policy api was successful. However when I use that general user to list channels, there was none. In the log I found: 
~~~
mainflux-users         | {"level":"info","message":"Method identify for token  eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODcyNzMwMzgsImlhdCI6MTY4NzE4NjYzOCwiaWRlbnRpdHkiOiJ1c2VyMUBleGFtcGxlLmNvbSIsImlzcyI6ImNsaWVudHMuYXV0aCIsInN1YiI6IjM1NGM4NWMzLWM5YzUtNDdiYS1hMWQ1LThlNTZhMjIyOTQ0YyIsInR5cGUiOiJhY2Nlc3MifQ.OYbzPmSVXV1Q4HiAyyIahpzAiNziH81yeacawLmC2aywxEJ5Z6bPhRpbvbYIIH0ox_FJWkc_d97i61DoDxSA_A with id 354c85c3-c9c5-47ba-a1d5-8e56a222944c took 390.803µs to complete without errors.","ts":"2023-06-19T16:14:15.052695124Z"}
mainflux-users         | {"level":"warn","message":"Method authorize for subject 354c85c3-c9c5-47ba-a1d5-8e56a222944c on object things for action g_list with entity group took 2.141715ms to complete with error: failed to perform authorization over the entity.","ts":"2023-06-19T16:14:15.055985846Z"}
mainflux-things        | {"level":"info","message":"Method list_channels using token  eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODcyNzMwMzgsImlhdCI6MTY4NzE4NjYzOCwiaWRlbnRpdHkiOiJ1c2VyMUBleGFtcGxlLmNvbSIsImlzcyI6ImNsaWVudHMuYXV0aCIsInN1YiI6IjM1NGM4NWMzLWM5YzUtNDdiYS1hMWQ1LThlNTZhMjIyOTQ0YyIsInR5cGUiOiJhY2Nlc3MifQ.OYbzPmSVXV1Q4HiAyyIahpzAiNziH81yeacawLmC2aywxEJ5Z6bPhRpbvbYIIH0ox_FJWkc_d97i61DoDxSA_A took 10.870875ms to complete without errors.","ts":"2023-06-19T16:14:15.062003788Z"}
~~~
From the logs it appears that the call was checking policies in users service. Should it be checking the policies in Things service though?

**Comment by dborovcanin** [comment]
OK, let's go step by step.
- First, we apologize for not having decent docs yet (it's still WIP), this should all be explained there. @rodneyosodo Please check this thread and try to update the docs accordingly. We also need to sort out some of the available actions and fix bugs before the upcoming 0.14 release.
- Channel = Things group, just like you noticed. We kept Channel terminology for backward compatibility reasons.
- Users have groups, but it is related to user management, not Things, and your focus is most likely on Things.
- Thing sharing is a simple process of adding things or users to the thing group - Channel.
- If you want to list channels, you simply list those that you own or you are a member of or both.

**Comment by revozhang** [comment]
@dborovcanin Thank you! Now I understand.

**Comment by dborovcanin** [comment]
@revozhang Should we close this one?

**Comment by revozhang** [comment]
Close the issue.
