### ISSUE TITLE
CoAP get-request does not receive any data 

### ISSUE THREAD

**Issue by cdrcknz** [Mainflux/mainflux-lite#1828]
**BUG REPORT**

1. What were you trying to achieve?

- Our goal is to have NB-IoT/LTE Cat-M1 connected device communicate with mainflux using CoAP over UDP.
- Post-request from the devices (clients) work fine
- Get-requests from the devices do not return any data
- Get-requests from libcoap do not return any data

3. What are the expected results?

- We expected to get a JSON message with a URL that can be used for OTA updates:
- 
[
  { bn: ‘urn:dev:864475040015538’, bt: 1687258025.764, bu: ‘s’ },
  { u: ‘OTA’, vs: ‘http://example.com/test_file.txt’ }
]

5. What are the received results?

- The devices (clients) only receive "2.05" without any piggybacked data nor any notification afterwards

7. What are the steps to reproduce the issue?

- libcoap cli: 
coap-client -v 8 -O 6,0x00 -O 17,0x32 -t 50 -o - -m get  'coap://<coap-server>/channels/<channel_id>/messages?auth=<auth_key>     

- devices:
ESP32S3 with lobaro-coap library and a BG770 modem using AT-commands.

9. In what environment did you encounter the issue?

- We encountered the issue both on Mac and on an ESP32 microcontroller with a BG770 mofrm

11. Additional information you deem important:

Logs from CoAP-Adapter:
│ {"level":"info","message":"Method subscribe to 91337d85-1cf8-4a3e-950f-061287ef8d0b.channels.91337d85-1cf8-4a3e-950f-061287ef8d0b.messages for client c3 took 1.391325ms to complete without errors.","ts":"2023-06-22T09:37:09.87874449Z"}       │

│ {"level":"info","message":"Method subscribe to 91337d85-1cf8-4a3e-950f-061287ef8d0b.channels.91337d85-1cf8-4a3e-950f-061287ef8d0b.messages for client c4 took 1.403559ms to complete without errors.","ts":"2023-06-22T09:37:10.728873172Z"}      │

│ {"level":"info","message":"Method subscribe to 91337d85-1cf8-4a3e-950f-061287ef8d0b.channels.91337d85-1cf8-4a3e-950f-061287ef8d0b.messages for client c5 took 1.412364ms to complete without errors.","ts":"2023-06-22T09:37:11.798753724Z"}      │

│ {"level":"warn","message":"Can't set response: timeout: retransmission(4) was exhausted","ts":"2023-06-22T09:37:23.803498263Z"}

**Comment by drasko** [comment]
Thanks @cedriciox for this detailed bug report. We will try to reproduce and see what is happening - i.e. is there a problem in CpAP server / lib, Mainflux adapter or `cloap-cli` tool.

Probably @dborovcanin will take a look at it, as he is an author of `coap-cli`.

**Comment by cdrcknz** [comment]
Issue can be closed. 
We are using LobaroCoAP as a CoAP backbone. The library mishandled the observation requests.

**Comment by drasko** [comment]
@cedriciox can you please explain this to us - what is this LobaroCOAP? Is this on the client device, and that was creating the problems? Can you confirm that Mainflux CoAP (in the cloud) is working fine?

**Comment by cdrcknz** [comment]
LobaroCoAP is a C library for embedded devices with a more open internal structure compared to libcoap.
The problem was created by lobaro not looking properly for a observation flag before deleting a pending CoAP interaction.
Adding a check for an oberservation flag on a get-request solved the issue.

Mainflux works fine

**Comment by drasko** [comment]
Great, thanks for clarification. Glad to hear that Mainflux works fine.
