### ISSUE TITLE
Is there a way to share twin between users? 

### ISSUE THREAD

**Issue by kozjax** [Mainflux/mainflux-lite#1853]
is there a way to share twin between users? 
I'm unable to find an api to add twin to group or share with users.

**Comment by drasko** [comment]
I am not sure we worked on this yet. Definitely, Twin service needs some love.

@kozjax are you using Twins service in some applications? I am curious, I would like to see the experiences people are having with it.

**Comment by dborovcanin** [comment]
Twins service will soon be moved to `contrib` repository. Since there have been no updates on this issue, I'm closing it for now. Please feel free to reopen if you need to.
