### ISSUE TITLE
Share the updated commands after installation. 

### ISSUE THREAD

**Issue by ManasviJaipurkar** [Mainflux/mainflux-lite#1859]
@nmarcetic , @janko-isidorovic @manuio , @anovakovic01 , @srados, @gesaleh ,@blokovi, @mteodor 

After installation what is the next procedure?
1. How to connect UI ?
2.What is exact output ?

**Comment by dborovcanin** [comment]
Please check https://docs.magistrala.abstractmachines.fr/getting-started/. Alternatively, you can use UI at `http://localhost:9095/ui/login` for things, channels, users, and group management.
