### ISSUE TITLE
Create Authorize for thing service in SDK

### ISSUE THREAD

**Issue by ianmuchyri** [Mainflux/mainflux-lite#1870]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
`Authorize()` for things service in the SDK. We only have [authorize()](https://github.com/mainflux/mainflux/blob/106b7105411670dcfcbe507f1a1727a4488960de/pkg/sdk/go/policies.go#L35) for user service  and [ThingCanAccess()](https://github.com/mainflux/mainflux/blob/106b7105411670dcfcbe507f1a1727a4488960de/pkg/sdk/go/policies.go#L212) for thing Service. `ThingCanAccess()` only checks a thing's policies over a channel. Possible use case: In the Mainflux-UI we require to know whether a user has various policy actions over a particular thing entity. For example: check if a user has a `c_delete` policy over a thing and disable the delete icon if they do not.
3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
must-have

**Comment by rodneyosodo** [comment]
You can use `ThingCanAccess` this is able to handle all authorizations for things service. How to use it
1. Check if a user has access to thing
	```go
	var areq = mfxsdk.AccessRequest{
		Subject:    "userID",
		Object:     "thingID",
		Action:     "c_delete",
		EntityType: "client",
	}
	```
2. Check if a user has access to channel
	```go
	var areq = mfxsdk.AccessRequest{
		Subject:    "userID",
		Object:     "channelID",
		Action:     "g_delete",
		EntityType: "group",
	}
	```
3. Check if thing has access to channel
	- using thingID
		```go
		var areq = mfxsdk.AccessRequest{
			Subject:    "thingID",
			Object:     "channelID",
			Action:     "m_read",
			EntityType: "client",
		}
		```
	- using thing Secret
		```go
		var areq = mfxsdk.AccessRequest{
			Subject:    "thingSecret",
			Object:     "channelID",
			Action:     "m_read",
			EntityType: "thing",
		}
		```
