### ISSUE TITLE
non-Admin user ListThingsByChannel not listing things shared with me

### ISSUE THREAD

**Issue by ianmuchyri** [Mainflux/mainflux-lite#1871]
**BUG REPORT**

1. What were you trying to achieve?
List things by channel ID. In the mainflux-UI, when logged in as a non-admin user, when I add a thing shared with me by an admin to one of my own channels when I list things connected to my channel, I cannot be able to see the things shared with me.
2. What are the expected results?
I would like the function [ThingsByChannel](https://github.com/mainflux/mainflux/blob/106b7105411670dcfcbe507f1a1727a4488960de/pkg/sdk/go/things.go#L94) in the Mainflux SDK to output even the users shared to me connected to that channel
3. What are the received results?
I can only view the things I own connected to that channel, and cannot view the things shared to me by the admin that are also connected to the channel.
4. What are the steps to reproduce the issue?

- Logged in as an admin, create thing1, channel1, and user1.
- Admin adds thing1 to channel1.
- Admin shares channel1 with user1.
- Log in as user1, you should be able to view thing1 since you have the appropriate policies.
- User1 creates channel2.
- User1 adds thing1 to channel2.
- User1 views ThingsByChannel using channel2 ID (they cannot be able to see thing1 connected to channel2)
-If admin views ThingByChannel using channel2 ID they can be able to see thing1 connected to channel2
5. In what environment did you encounter the issue?
Thing service
6. Additional information you deem important:

**Comment by dborovcanin** [comment]
This will be resolved by #2456.
