### ISSUE TITLE
List things with visibility set to all 

### ISSUE THREAD

**Issue by ianmuchyri** [Mainflux/mainflux-lite#1875]
**BUG REPORT**

1. What were you trying to achieve?
List things as a non-admin user with `visibility` set to `all`
2. What are the expected results?
List things I own and those shared with me 
3. What are the received results?
Lists only things shared with me
4. What are the steps to reproduce the issue?
set `visibility` to `all` in `ListThings` `page metadata`
5. In what environment did you encounter the issue?
Mainflux things
6. Additional information you deem important:

**Comment by dborovcanin** [comment]
We also should consider changing and renaming query parameters. There are 3 scenarios:

1. Resources I own
2. Resources shared with me
3. Resources shared by me

All these can be combined **with other queries** such as: `I own and shared with <IDs>`,  `shared with me by <IDs>`, `shared by me and owned by <IDs>`, and so on. We can take a subset of these combinations, but we need to find which subset of filters is the most beneficial for the end user.
