### ISSUE TITLE
Listing users as admin outputs the admin as one of the users

### ISSUE THREAD

**Issue by ianmuchyri** [Mainflux/mainflux-lite#1879]
**BUG REPORT**

1. What were you trying to achieve?
List Users
2. What are the expected results?
A list of active users while logged in as the admin. It should bring back all users except the admin.
3. What are the received results?
A list of active users including the admin 
![image](https://github.com/mainflux/mainflux/assets/100555904/7949ddec-002a-41a9-8982-8c418c274683)

4. What are the steps to reproduce the issue?

- Log in as the admin
- List users 
5. In what environment did you encounter the issue?
Mainflux Users service
6. Additional information you deem important:
when logged in as a non-admin user, it does not present this issue.
![image](https://github.com/mainflux/mainflux/assets/100555904/cef94f23-3a36-4727-841a-21a575507449)

**Comment by rodneyosodo** [comment]
This has been solved and can be closed @dborovcanin  [![asciicast](https://asciinema.org/a/z7uEv2IZxz32EJtSSaUktDRVT.svg)](https://asciinema.org/a/z7uEv2IZxz32EJtSSaUktDRVT)
