### ISSUE TITLE
authorization over Messeages in the reader service return `{"error":"failed to perform authorization over the entity","message":"something went wrong with the request"}`

### ISSUE THREAD

**Issue by ahmmkh** [Mainflux/mainflux-lite#1920]
**BUG REPORT**

1. What were you trying to achieve?
i wanted to read messages from postgres reader it doesn't read unless i  send a message first
2. What are the expected results?
that the postgres reader service returns a list of messages 
3. What are the received results?
`{"error":"failed to perform authorization over the entity","message":"something went wrong with the request"}`
4. What are the steps to reproduce the issue?
- send a message 
- wait 10 minutes
- try to read the messages
-
6. In what environment did you encounter the issue?

7. Additional information you deem important:
I think this behaviour is related to the MF_THINGS_CACHE_KEY_DURATION
what can i do if i want to be able to always read the messages from the reader service without having to send a message first

**Comment by Nitesh1794** [comment]
Hey ahmmkh !
Facing issue on installation of mainflux can you please guide me. What we need to do then than installation process given in documentation? At http://localhost i am getting 404 page not found error. Please help me.

**Comment by dborovcanin** [comment]
We were not able to replicate this issue. @ahmmkh Any updates on this?

**Comment by ahmmkh** [comment]
I didn't check this issue on the newer version. Until then I think we can close this issue @dborovcanin
