### ISSUE TITLE
Run tests fail

### ISSUE THREAD

**Issue by nintran52** [Mainflux/mainflux-lite#1945]
**BUG REPORT**

1. What were you trying to achieve?
- Run testing
3. What are the expected results?
- Pass all testing
4. What are the received results?
- Some testing fail
5. What are the steps to reproduce the issue?
- run `make test`
6. In what environment did you encounter the issue?
- Local
7. Additional information you deem important:
- I have checked the log, and there are many testing functions that are missing mock data
![Screenshot 2023-11-11 at 16 12 55](https://github.com/mainflux/mainflux/assets/92280633/ec67b4aa-da0d-4490-909e-f2ddf083fa4a)

**Comment by SammyOina** [comment]
The project is being moved here https://github.com/absmach/magistrala

**Comment by drasko** [comment]
Migration is still ongoing, will be announced once everything is ready.

**Comment by rodneyosodo** [comment]
All tests are passing https://github.com/absmach/magistrala/actions/workflows/build.yml

**Comment by rodneyosodo** [comment]
@dborovcanin this should be closed

**Comment by dborovcanin** [comment]
Closing this one as solved. @nintran52 If problems persist, please reopen or create a new one.
