### ISSUE TITLE
Multiple Services Failing to Start Due to NATS Connection Issues in Docker Compose Setup

### ISSUE THREAD

**Issue by ahmmkh** [Mainflux/mainflux-lite#1948]
---

**BUG REPORT**

1. **What were you trying to achieve?**

   Running the application using the Docker Compose command `docker compose --profile nats_nats -p mainflux_mainflux_git_master_ -f docker/docker-compose.yml up -d`.

2. **What are the expected results?**

   All services starting successfully without encountering errors.

3. **What are the received results?**

   Multiple services including `nginx`, `http`, `ws`, `coap`, `mqtt`, `things`, `user`, and others are failing to start and continuously restarting. The issue is primarily related to an inability to connect to the NATS service.

4. **What are the steps to reproduce the issue?**

   - Execute the Docker Compose command: `docker compose --profile nats_nats -p mainflux_mainflux_git_master_ -f docker/docker-compose.yml up -d`.
   - Observe the failure of various services to start, as they continuously restart.
   - Review the logs for these services, focusing on errors related to connections with the NATS service.

5. **In what environment did you encounter the issue?**

   - Docker version: 24.0.7, build afdd53b
   - Operating System: Ubuntu 22.04.3 LTS (GNU/Linux 6.2.0-1012-aws x86_64)
   - Additional environment details: [Any other relevant details]

6. **Additional information you deem important:**

   - The main issue appears to be the services' inability to connect to the NATS service.
   - all envs are the defaults from the .env file

7. **Service-Specific Logs**

   - **Nginx Service Log:**
     - **Excerpt:** `...host not found in upstream "mqtt-adapter:8080"...`

   - **Mainflux/HTTP Service Log:**
     - **Excerpt:** `...failed to connect to message broker: dial tcp [::1]:4222: connect: cannot assign requested address...`

   - **Mainflux/WS Service Log:**
     - **Excerpt:** `...Failed to connect to message broker: dial tcp [::1]:4222: connect: cannot assign requested address...`

   - **Mainflux/CoAP Service Log:**
     - **Excerpt:** `...failed to connect to message broker: nats: no servers available for connection...`

   - **Mainflux/MQTT Service Log:**
     - **Excerpt:** `...failed to connect to message broker: dial tcp [::1]:4222: connect: cannot assign requested address...`

   - **Mainflux/Things Service Log:**
     - **Excerpt:** `...failed to create things service: redis: invalid URL scheme: nats...`

   - **Mainflux/User Service Log:**
     - **Excerpt:** `...failed to create users service: redis: invalid URL scheme: nats...`

---

**Comment by ahmmkh** [comment]
@drasko can you help out?

**Comment by drasko** [comment]
@ahmmkh we are slowly but surely moving to [Magistrala](https://github.com/absmach/magistrala) fork, a rebranded Mainflux under our new company in Paris, France. To be announced yet, when we finish all the tedious transition work.

You can try it out over there, should be functional.
