### ISSUE TITLE
Feature: Removing Domain ID from domain endpoints

### ISSUE THREAD

**Issue by arvindh123** [Mainflux/mainflux-lite#1954]
### Is your feature request related to a problem? Please describe.

If I have JWT for `domain1`
If I accidently/voluntarily send request to  `domain2`
`/domains/domain2/users/assign`
Any how it won't work, But an unwanted request is send to spicedb to validate the policy

This feature avoids this unwanted request ,improves DevX and gives more clarity about domains 

### Describe the feature you are requesting, as well as the possible use case(s) for it.

At present we have following endpoints in domains :

POST `/domains` Create Domain
GET `/domains` list all Domains
GET `/domains/<domainID>` View Domain
GET `/domains/<domainID>/permission` View Domain permission
PATCH `/domains/<domainID>`  Update Domain
POST `/domains/<domainID>/enable` Enable Domain
POST `/domains/<domainID>/disable`  Disable Domain
POST `/domains/<domainID>/users/unassign`  unassign users from domain
POST /domains/<domainID>/users/assign` assign users from domain

We have `domain ID` in JWT Token ,
So instead of passing `domainID `in URL ,  we can reuse the domain ID provided in token

If we reuse the domain id provided in token , then endpoints can be changes
Endpoints looks more clear like below

GET `/domains` list all accessible Domains
POST `/domain` Create Domain
GET `/domain` View Domain
GET `/domain/permission` View Domain permission
PATCH `/domain` Update Domain
POST `/domain/enable` Enable Domain
POST `/domain/disable`  Disable Domain
POST `/domain/users/unassign`  unassign users from domain
POST `/domain/users/assign` assign users from domain

We have similar concept in users service in `MF 0.13`
GET `/users` Get Current logged in users
POST `/users` updates current logged in user

The above two request uses user id in JWT token
Similarly to users service, In Domains (namespace), once we logged into namespace, the token is enough to do operation on namespace, No need to mentioned the namespace id in request

By removing domain id from domain request , DevX experience  will improved,
Developer/User don't need to care about the domain id while sending domains service

This also avoids sending invalid request backend
For Example:
If I have JWT for `domain1`
If I accidently/voluntarily send request to  `domain2`
`/domains/domain2/users/assign`
Any how it won't work, But an unwanted request is send to spicedb to validate the policy
**If we use the domain Id in token , this kind of requests can be avoid**

### Indicate the importance of this feature to you.

Must-have

**Comment by WashingtonKK** [comment]
This is a great idea @arvindh123, we need to remove the domain ID from the domain endpoints since it is already in the token.

**Comment by WashingtonKK** [comment]
Can we have these as endpoint instead @arvindh123:

| Method | Endpoint                             | Description                     |
|--------|--------------------------------------|---------------------------------|
| GET    | `/domains`                           | List all accessible Domains     |
| POST   | `/domains`                           | Create Domain                   |
| GET    | `/domains/domain`                    | View Domain                     |
| GET    | `/domains/domain/permissions`         | View Domain permission          |
| PATCH  | `/domains/domain`                    | Update Domain                   |
| POST   | `/domains/domain/enable`             | Enable Domain                   |
| POST   | `/domains/domain/disable`            | Disable Domain                  |
| POST   | `/domains/domain/users/unassign`     | Unassign users from Domain      |
| POST   | `/domains/domain/users/assign`       | Assign users to Domain          |

What do you think @arvindh123

**Comment by arvindh123** [comment]
> Can we have these as endpoint instead @arvindh123:
> 
> Method	Endpoint	Description
> GET	`/domains`	List all accessible Domains
> POST	`/domains`	Create Domain
> GET	`/domains/domain`	View Domain
> GET	`/domains/domain/permissions`	View Domain permission
> PATCH	`/domains/domain`	Update Domain
> POST	`/domains/domain/enable`	Enable Domain
> POST	`/domains/domain/disable`	Disable Domain
> POST	`/domains/domain/users/unassign`	Unassign users from Domain
> POST	`/domains/domain/users/assign`	Assign users to Domain
> What do you think @arvindh123

@WashingtonKK I agree with you 

with some changes 

| Method | Endpoint                             | Description                     |
|--------|--------------------------------------|---------------------------------|
| GET    | `/domains`                           | List all accessible Domains     |
| POST   | `/domains`                           | Create Domain                   |
| GET    | `/domain`                    | View Domain                     |
| GET    | `/domain/permissions`         | View Domain permission          |
| PATCH  | `/domain`                    | Update Domain                   |
| POST   | `/domain/enable`             | Enable Domain                   |
| POST   | `/domain/disable`            | Disable Domain                  |
| POST   | `/domain/users/unassign`     | Unassign users from Domain      |
| POST   | `/domain/users/assign`       | Assign users to Domain          |

**Comment by WashingtonKK** [comment]
Thanks

**Comment by dborovcanin** [comment]
Tokens are transparent from the API perspective, so having ID is more aligned with REST approach and does not hurt. While we need to compare domain ID with the domain from the token, that's not a problem. I.e. let's keep it as it is for the time being:

| method | endpoint                    | description                 |
| ------ | --------------------------- | --------------------------- |
| GET    | /domains                    | List all accessible Domains |
| POST   | /domains                    | Create Domain               |
| GET    | /domain/{id}                | View Domain                 |
| GET    | /domain/{id}/permissions    | View Domain permission      |
| PATCH  | /domain/{id}                | Update Domain               |
| POST   | /domain/{id}/enable         | Enable Domain               |
| POST   | /domain/{id}/disable        | Disable Domain              |
| POST   | /domain/{id}/users/unassign | Unassign users from Domain  |
| POST   | /domain/{id}/users/assign   | Assign users to Domain      |

If we decide to make a super-admin act without domains, or we change our approach to tokens, this API makes it more resilient and intuitive to use. @drasko Please check and leave your comments.

**Comment by drasko** [comment]
I agree with @dborovcanin, please keep `id` in the API - tokens might evolve and change. Do not strongly couple API to token type. Also - admins might have different tokens and point to different IDs.

**Comment by WashingtonKK** [comment]
Thank you @drasko and @dborovcanin, I will close this issue now since we will not implement it.
