### ISSUE TITLE
Feature: Single endpoint to change status of domain

### ISSUE THREAD

**Issue by arvindh123** [Mainflux/mainflux-lite#1962]
### Is your feature request related to a problem? Please describe.

There are three different endpoint  (`/enabled` , `/disable`, `/freeze`) to change status of domain.

### Describe the feature you are requesting, as well as the possible use case(s) for it.

@dborovcanin recommendations :

We should probably do the following:
- ~separate enable and disable and freeze from soft delete~
- add delete endpoint - delete operation can't be undone
- add change-status endpoint for all other changeable statuses.

### Indicate the importance of this feature to you.

Must-have

**Comment by dborovcanin** [comment]
Due to the recent discussion (https://github.com/absmach/magistrala/pull/2127#discussion_r1542169662) and inactivity, this one will probably be discarded.

**Comment by dborovcanin** [comment]
Closing according to: https://github.com/absmach/magistrala/pull/2127#issuecomment-2063950842.
