### ISSUE TITLE
Bug: CoAP with TLS doesn't Support UDP

### ISSUE THREAD

**Issue by rodneyosodo** [Mainflux/mainflux-lite#1963]
### What were you trying to achieve?

Test coap server with TLS i.e providing certificate and key

### What are the expected results?

To work with TLS

### What are the received results?

```bash
cannot create new tls listener: cannot create new net tcp listener: unknown network udp
```

### Steps To Reproduce

Provide certificate and key when starting coap server

### In what environment did you encounter the issue?

main branch

### Additional information you deem important

https://github.com/absmach/magistrala/blob/ff12f7fca35534a2b012ed10d320b58ed13eb46a/internal/server/coap/coap.go#L58C1-L60C6

```go
go func() {
	errCh <- gocoap.ListenAndServeTCPTLS("udp", s.Address, tlsConfig, s.handler)
}()
```

This works when the network is TCP and not UDP

**Comment by drasko** [comment]
@dborovcanin @1998-felix can someone please take a look at this issue

**Comment by felixgateru** [comment]
DTLS termination will be carried out on mproxy and is handled by https://github.com/absmach/mproxy/pull/60

**Comment by dborovcanin** [comment]
Blocked by https://github.com/absmach/mproxy/pull/60.

**Comment by rodneyosodo** [comment]
Resolved by https://github.com/absmach/magistrala/pull/2139
