### ISSUE TITLE
Feature: API Error Handling

### ISSUE THREAD

**Issue by SammyOina** [Mainflux/mainflux-lite#1964]
### Is your feature request related to a problem? Please describe.

current error handling relies on having a series of contains() checks for different wrapped errors before assigning an error code and encoding an error response. This results in relatively large switch statements for each case.

### Describe the feature you are requesting, as well as the possible use case(s) for it.

I propose a new error interface for API errors more specifically.
```go
func New(err string) error{}
type Error interface{
  WithCode(code int) error
 Code() int
 Error() string
 }
 ```
 This will enable errors to be assigned status codes at the point of creation on the API and remove the need for additional checks before encoding an error response.

### Indicate the importance of this feature to you.

Must-have

**Comment by arvindh123** [comment]
@SammyOina ,
@absmach/magistrala 

I had an alternative idea , which is to check only for top level and next to the top level errors in wrapped errors
Service error or API handler errors will be in top level , I guess which is sufficient to send response in API

**Comment by SammyOina** [comment]
@arvindh123 with my proposal we can still use the top level error, the improvement I propose is to eliminate the need for a check before assigning an error code
