### ISSUE TITLE
Feature: Add WebSockets support to Readers

### ISSUE THREAD

**Issue by dborovcanin** [Mainflux/mainflux-lite#1966]
### Is your feature request related to a problem? Please describe.

Currently, there is no way of streaming live data using Magistrala Reders. Since this feature is needed by the UI, WebSockets seems to be a good protocol of choice.

### Describe the feature you are requesting, as well as the possible use case(s) for it.

UI live dashboards will require a stream of live data from the MG internal broker to the UI. We will use Readers for that, providing not only options to access the database, but also to stream data to the client using a WebSocket connection.

### Indicate the importance of this feature to you.

Should-have

**Comment by arvindh123** [comment]
@dborovcanin 
I Think , Polling is enough for now.  It fits for all the cases.

I have some question in mind related to sending message data in WebSocket
1. How will the requests send to reader? Does it have filters like limit, order by time, name.? If user want to change any of the filter then how the request will be updated ? 
2. How frequently messages are sent by Reader in response ? 
3. What are the values customer will get by showing near real time messages in UI ? 

I think we should have bidirectional communication between the UI and reader

**Comment by dborovcanin** [comment]
The idea was that the Reader subscribes to the particular NATS topic on demand and streams whatever it is receiving to the use through WS connection. The main benefit for the user is not to show near-real-time messages, but near-real-time updates on the dashboards.

**Comment by rodneyosodo** [comment]
Since readers are reading messages from a channel why not add the ability for a user to stream messages using websocket?

Then UI can connect to WS to receive near real-time messages and connect to readers to receive store/past messages

**Comment by rodneyosodo** [comment]
https://github.com/ultravioletrs/mainflux-ui/issues/25#issuecomment-1727861743

**Comment by dborovcanin** [comment]
Since readers are not meant to be used for real-time processing, this can be either offloaded to a new component that directly consumes from the internal message bus, or we can stick with pooling for a near-real-time approach. Closing.
