### ISSUE TITLE
Feature: Handle errors in things gRPC server and client

### ISSUE THREAD

**Issue by arvindh123** [Mainflux/mainflux-lite#1967]
### Is your feature request related to a problem? Please describe.

Things gRPC doesn't handles the authorization errors,  so for improper authorization request, get unhandled error which is not understandable and exposing backend logs 

### Describe the feature you are requesting, as well as the possible use case(s) for it.

Handling of error in things gRPC server and client will solve the above mentioned issue

### Indicate the importance of this feature to you.

Must-have

**Comment by JeffMboya** [comment]
This has been resolved. On the server side, in the encodeError function, if the error is of type svcerr.ErrAuthorization, a gRPC status error with codes.PermissionDenied is returned. On the client side, in the decodeError function, if the gRPC status code is codes.PermissionDenied, it wraps the error into svcerr.ErrAuthorization: So, it doesn't seem like an improper authorization request would result in an unhandled error.
