### ISSUE TITLE
Bug: New user to the platform sees all users

### ISSUE THREAD

**Issue by rodneyosodo** [Mainflux/mainflux-lite#1976]
### What were you trying to achieve?

Bootstrap magistrala i.e add random users, things and channels then create a new user and try to view the index page using the UI

### What are the expected results?

To be able not to see any users since I have logged in on a new domain i.e I should not be able to see the users

### What are the received results?

A new user on the platform can see all users in other domains. Is this the intended behaviour? If we are to have a multi-tenant platform, then this is not the intended behaviour. A user should only be able to see users in his/her domain.

### Steps To Reproduce

1. Start magistrala

	```bash
	make run
	```

2. Run the following command to create different users at least twice 

	```bash
	go run tools/e2e/cmd/main.go -n 10 -N 1
	```
3. Create a new user

	```bash
	magistrala-cli users create demo demo@demo.mail 12345678
	```

4. Login the user to UI and view the dashboard

### In what environment did you encounter the issue?

Git commit - https://github.com/absmach/magistrala/commit/492ce14baff1d40ef4ff567e6955690219212e44
Docker Compose version 2.23.3
Docker version

> 	Client:
> 	 Version:           24.0.7
> 	 API version:       1.43
> 	 OS/Arch:           linux/amd64
> 	
> 	Server:
> 	 Engine:
> 	  Version:          24.0.7
> 	  API version:      1.43 (minimum version 1.12)

### Additional information you deem important

![image](https://github.com/absmach/magistrala/assets/28790446/edf65074-8180-4d6c-921b-9462e5c82b46)

**Comment by dborovcanin** [comment]
The user should be able to filter all users (so they can be invited to join the domain), but not to see the count. Only superadmins should be able to see counts of all the users on the platform.

**Comment by dborovcanin** [comment]
While this is fixed on the UI, the user should not be able to see the count of all the users in the platform using the API.

**Comment by dborovcanin** [comment]
@1998-felix Please test, this one should be resolved.

**Comment by felixgateru** [comment]
The listing of users was modified by this pr: https://github.com/absmach/magistrala/pull/2168 which enables returning only basic information about users on the platform, but the total is still visible from the api  for pagination.

**Comment by dborovcanin** [comment]
Only the `total` field (revealing the total number of users in the platform) is relevant here, but other than that, this ticket can be closed. Once Search PR #2288 is merged, this ticket can be closed.
