### ISSUE TITLE
Bug: Sending invitations to members who have been assigned to the domain directly shouldn't be possible

### ISSUE THREAD

**Issue by ianmuchyri** [Mainflux/mainflux-lite#1977]
### What were you trying to achieve?

While logged in as a super admin, I was able to assign a user to a domain directly. However, after the user is added to the domain, I am still able to send an invitation to the user to join the domain

### What are the expected results?

I should not have been able to send an invite to the user since they are already members of the domain

### What are the received results?

I was able to send an invite to a user who was already a member of the domain since they were assigned to the domain directly by the super admin, but this was not reflected in the invitations service.

### Steps To Reproduce

1. create a domain
2. log in with super admin user
3. create a user
4. assign a user to a domain
5. send an invitation to the same user to join the domain

### In what environment did you encounter the issue?

Magistrala invitations service

**Comment by dborovcanin** [comment]
We need to add the API to support fetching **usernames** for other users, as well. Usernames are required to make the UI nicer. Either fetch the username by ID or fetch both username and ID in a single filtering request when sending the invitation.
