### ISSUE TITLE
Bug: User is able to see superAdmin in listUsers

### ISSUE THREAD

**Issue by ianmuchyri** [Mainflux/mainflux-lite#1982]
### What were you trying to achieve?

When listing all users, the `superAdmin` is visible to all users who are logged in

### What are the expected results?

The `superAdmin` should not be visible to other users on the system

### What are the received results?

A list of all users in the system including the `superAdmin`

### Steps To Reproduce

1. create a user
2. fetch token 
3. list users

### In what environment did you encounter the issue?

Magistrala users service

**Comment by ianmuchyri** [comment]
Related to this issue in the UI https://github.com/absmach/magistrala-ui/issues/38

**Comment by JeffMboya** [comment]
This issue was resolved. A user is no longer able to view a user with the role of admin.
