### ISSUE TITLE
Feature: Add username and domain name variables to ListInvitations Return value

### ISSUE THREAD

**Issue by ianmuchyri** [Mainflux/mainflux-lite#1987]
### Is your feature request related to a problem? Please describe.

When I list Invitations, I get the user ID and domain ID, and It's currently not possible to view a user with their ID if a user is not a super admin. Thus when displaying on the UI we display ID's which is not pleasing

![image](https://github.com/absmach/magistrala/assets/100555904/f78aad35-1621-493c-b129-3d00a3f16c2e)

### Describe the feature you are requesting, as well as the possible use case(s) for it.

Return the user name and domain name as part of the return value for listing invitations

### Indicate the importance of this feature to you.

Must-have

**Comment by dborovcanin** [comment]
We do not need only a username, we also need a domain name.

**Comment by dborovcanin** [comment]
This is a duplicate of #1977. Closing.

**Comment by arvindh123** [comment]
Something like at here https://github.com/arvindh123/magistrala/blob/edecffd3bf26015f02cce7593152c1c193e7f03a/users/service.go#L117-L136 
will work

```go
func (svc service) ViewClient(ctx context.Context, token, id string) (mgclients.Client, error) {
	tokenUserID, err := svc.Identify(ctx, token)
	if err != nil {
		return mgclients.Client{}, err
	}

	if tokenUserID != id {
		if err := svc.checkSuperAdmin(ctx, tokenUserID); err == nil {
			client, err := svc.clients.RetrieveByID(ctx, id)
			if err != nil {
				return mgclients.Client{}, errors.Wrap(svcerr.ErrViewEntity, err)
			}
			client.Credentials.Secret = ""
			return client, nil
		}
	}
	client, err := svc.clients.RetrieveBasicInfoByID(ctx, id)
	if err != nil {
		return mgclients.Client{}, errors.Wrap(svcerr.ErrViewEntity, err)
	}
	client.Credentials.Secret = ""
	return client, nil
}
```
