### ISSUE TITLE
Adding duplicate users results in double policies

### ISSUE THREAD

**Issue by dborovcanin** [Mainflux/mainflux-lite#1989]
### What were you trying to achieve?

I'm trying to add a user with a duplicate username. I got rejected by the Users svc (code 409), but also there is an outstanding policy created in SpiceDB.

### What are the expected results?

I expect no policies added in case User creation fails.

### What are the received results?

The user is not created, but the policy is.

### Steps To Reproduce

Build the latest Users and Auth services and start docker composition. Use API to add a new user. Try again the same create request with the same user.

### In what environment did you encounter the issue?

I'm using Docker version 25.0.7, compose version 2.23.3, and the latest master build as of the time of issuing this ticket.

**Comment by arvindh123** [comment]
@dborovcanin 
In spicedb delete relation are not actually deleted from database , instead delete transaction id is used to soft delete the item

![Image](https://github.com/absmach/magistrala/assets/30824765/349462a3-a91a-4aa4-b1b5-6e87628cdb70)

Here you can see the column `delete_xid`, 
These column have value  of max int - `9223372036854775807` which means relationship exists 
In last two rows you can see `delete_xid` have `858` and `860`, which means these relationships are delete 

If `delete_xid` column doesn't have max int - `9223372036854775807` , then the relationship are doesn't exists

To double check it , I  tried to list them I could not see these delete user id in result

![Image](https://github.com/absmach/magistrala/assets/30824765/5bc6c2f1-57bb-4a1d-8809-469eebfac4dd)

So they are delete from policy but not removed from database rows

**Comment by dborovcanin** [comment]
Got it. OK, so this is not a bug, and works as intended? If yes, please close it. Is there an option to do the cleanup and remove the deleted policies from time to time (say, every day or something)?

**Comment by arvindh123** [comment]
Yes, It is not bug and works as intended. 
I guess spicedb will do the cleanup job periodically and I'm not sure. I need to confirm with spicedb docs
