### ISSUE TITLE
Bug: Error handling is not working properly

### ISSUE THREAD

**Issue by dborovcanin** [Mainflux/mainflux-lite#1990]
### What were you trying to achieve?

I'm trying to register a new user with an already existing email.

### What are the expected results?

I expect to see `conflict` (409).

### What are the received results?

I get `internal error` (500).

### Steps To Reproduce

Build Docker images from the `main`; register user; try to register the same user again.

### In what environment did you encounter the issue?

Docker version 24.0.7 and compose 2.23.3,

### Additional information you deem important

This is related to changes introduced [here](https://github.com/absmach/magistrala/commit/1f087bf42c5217cbdb7427af3040c85b04084de4#diff-3cc9b948448aaf65a20333206d53f08660be712a156ddcb7c0ab5d1a3f1e3e64R27); since our internal `errors.Contains`  does not work well with joined errors (we should use native `errors.Unwrap`).

**Comment by JeffMboya** [comment]
This bug has been resolved. Now, when trying to register a new user with an already existing email, the system correctly returns a conflict (409) instead of an internal error (500) as shown below.
![Screenshot from 2024-03-26 15-37-35](https://github.com/absmach/magistrala/assets/44696487/b5c349fa-d8c9-4509-beda-8c57d7431e77)

**Comment by arvindh123** [comment]
@JeffMboya  Could you please add an example with cURL, so that we can see the HTTP status code in response

**Comment by JeffMboya** [comment]
@arvindh123 here is an example with cURL
![Screenshot from 2024-03-26 18-40-56](https://github.com/absmach/magistrala/assets/44696487/9e42b847-692c-4f8f-a6ee-cf3b4332fec6)
