### ISSUE TITLE
Feature: Login With Username

### ISSUE THREAD

**Issue by rodneyosodo** [Mainflux/mainflux-lite#1992]
### Is your feature request related to a problem? Please describe.

You are only able to log in using your identity and password. Username and password login is not supported

### Describe the feature you are requesting, as well as the possible use case(s) for it.

To enable users to log in using their (identity or username) and password

### Indicate the importance of this feature to you.

Nice-to-have

### Anything else?

This will introduce a username field to users it will be unique and the name field will still remain

**Comment by dborovcanin** [comment]
Usernames are unique, but nullable (which is good for migrations, but also OAuth or any  3rd-party identity providers). Emails are unique and required, usernames are unique and nullable. Usernames can't have the same format as emails, so we can differentiate between them during login. This will be addressed in #2426.
