### ISSUE TITLE
 Refactoring Error Handling & Return Varaibles 

### ISSUE THREAD

**Issue by arvindh123** [Mainflux/mainflux-lite#1998]
**ENHANCEMENT**
1. Describe the enhancement you are requesting. Enhancements include:
   - code refactor
  
### Suggestion 1:
In a substantial portion of the codebase, functions tend to return the outcome of a call directly, neglecting the handling of potential errors stemming from these calls.
### Example:
```go
func (svc Service) Function1(param1 string) (client, error) {
   return svc.anotherService.Call(param1)
}
```

### Desired Solution:
Refactor these functions to incorporate error handling:
```go
func (svc Service) Function1(param1 string) (client, error) {
   client, err := svc.anotherService.Call(param1)
   if err != nil {
      return client{}, errors.Wrap(svcerr.CallErr, err) 
   }
   return client, nil 
}
```
### Suggestion 2:
Function with return struct/variable and error should return empty struct/variable on error return 

### Not looks function
```go
func (svc service) ServiceCall(param1 string) (client, error) {
    cli, err := svc.anotherServiceCall(param1)

    if err != nil {
        return cli, errors.Wrap(svcerr.RepoCall, err)
    }

    return cli, nil
}
```
### Looks good function
```go
func (svc service) ServiceCall(param1 string) (client, error) {
    cli, err := svc.anotherServiceCall(param1)

    if err != nil {
        return client{}, errors.Wrap(svcerr.RepoCall, err)
    }

    return cli, nil
}
```
2. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).
must-have

**Comment by WashingtonKK** [comment]
This is addressed in this PR: https://github.com/absmach/magistrala/pull/2119

**Comment by dborovcanin** [comment]
This https://github.com/absmach/magistrala/pull/2088#discussion_r1557171749 should also be resolved in this issue.

**Comment by WashingtonKK** [comment]
It is already being solved in this PR: https://github.com/absmach/magistrala/pull/2119
