### ISSUE TITLE
Authorization Failure on /things/bulk Endpoint with Bearer Token 

### ISSUE THREAD

**Issue by ahmmkh** [Mainflux/mainflux-lite#1999]
---

**BUG REPORT**

1. **What were you trying to achieve?**
   - I was attempting to create a 'thing' using the `/things/bulk` API endpoint after generating a bearer authentication token using the `users/tokens/issue` endpoint.

2. **What are the expected results?**
   - The expected result was the successful creation of a 'thing' using the provided bearer authentication token without any authorization errors.

3. **What are the received results?**
   - Instead of successful creation, I received an error message: 
     ```
     {
         "error": "failed to perform authorization over the domain",
         "message": "failed to perform authorization over the entity"
     }
     ```

4. **What are the steps to reproduce the issue?**
   - Step 1: Generate a bearer authentication token using the `users/tokens/issue` endpoint.
   - Step 2: Attempt to create a 'thing' using the `/things/bulk` API endpoint with the generated token.

5. **In what environment did you encounter the issue?**
   - Docker version: 24.0.7, build afdd53b
 -Operating System: Ubuntu 22.04.3 LTS (GNU/Linux 6.2.0-1012-aws x86_64)

6. **Additional information you deem important:**
   - Server logs for the things service showed the following:
     ```
     {"level":"warn","message":"Method create_things 0 things using token [token redacted] took 874.37µs to complete with error: failed to perform authorization over the entity : failed to perform authorization over the domain.","ts":"2023-11-27T21:49:42.429995648Z"}
     ```

---

**Comment by ahmmkh** [comment]
my best guess is that the jwt tokenizer is not working properly because both the userField and domainField claims are missing in the AccessToken I received

**Comment by arvindh123** [comment]
Hello @ahmmkh 

Things can be created only under a domain , i.e. JWT with domain field 

To do operations like view, update domain ,CRUD things, groups,channels, share ,etc. , a token with `domain` claim is needed 

Here I will write cURL request for creating a thing 

Step 1 : Get User Token
```bash
curl --location 'http://localhost/users/tokens/issue' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--data-raw '{
        "identity": "user1@example.com",
        "secret": "12345678",
        "domain_id": ""
}'
```
In response you will get a access and refresh token
In that response jwt token `domain` claim will be empty
This token can be use to create and list domain 
To do operations like view, update domain ,CRUD things, groups,channels, share ,etc. , a token with `domain` claim is needed 



Step 2:  Create New Domain 
```bash
curl --location 'http://localhost/domains' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <ACCESS_TOKEN> ' \
--data '{
    "name" :"Domain 1",
    "alias":"domain_1"
}
'
```

Step 3: Try to List Domain with same token (without domain, as mentioned earlier this token can be used create and list domain ) 
```
curl --location 'http://localhost/domains' \
--header 'Authorization: Bearer <TOKEN>'
```
**Copy the domain ID**


Step 4:  Get New Token with Domain claim ,

There are two ways to get token with Domain claim

Way 1 :
This way can be used if refresh token is expired 

 ```bash
curl --location 'http://localhost/users/tokens/issue' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--data-raw '{
        "identity": "user1@example.com",
        "secret": "12345678",
        "domain_id": "copied_domain_id_in_step_3"
}'
```
way 2 : 
This way can be used if refresh token is not expired

```
curl --location 'http://localhost/users/tokens/refresh' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer <REFRESH_TOKEN>' \
--data '{
        "domain_id": "copied_domain_id_in_step_3"
}'
```
**This way also use to switch from one domain to another domain**

**send request to `users/token/refresh` with empty json body , to get same domain access_token / to renew access_token after its expiry**
```
curl --location 'http://localhost/users/tokens/refresh' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer <REFRESH_TOKEN>' \
--data '{}'
```

Step 5: Create Things with new access token got in previous step

**Comment by ahmmkh** [comment]
well I tried to create a domain in the /domain endpoint you mentioned but it returns 404. @arvindh123

**Comment by arvindh123** [comment]
Hello @ahmmkh 

Domains are present in Auth Service
Auth HTTP server is running on port 8189 and GRPC server on port 8181 

If Magistrala is started using command `make run` from repo root directory.

Then Nginx will be configured with  [`docker/nginx/nginx-key.conf`](https://github.com/absmach/magistrala/blob/main/docker/nginx/nginx-key.conf#L96-L114) 

Nginx reverse proxy traffic all traffic comes to this endpoint `http://localhost/domains` to auth service port 8189

Please make sure Nginx , Auth , and other magistrala service running properly 

If you still have problem, then try out the below command to create Domain
 
Make sure you have started Magistrala with `make run` command and auth service container port 8189 is exposed by docker 
```bash
curl --location 'http://localhost:8189/domains' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <ACCESS_TOKEN> ' \
--data '{
    "name" :"Domain 1",
    "alias":"domain_1"
}
```

Still if you face the same problem with creation of domain 
Please send here the create domain request, response and service logs If any available for future investigation.

**Comment by ahmmkh** [comment]
I initiated Magistrala by executing the provided command: `docker compose --profile nats_nats -f docker/docker-compose.yml up -d`. However, I encountered the "404 not found" error again even after specifying the port in my request to 8189, and there were no visible logs within the authentication service container, despite confirming that the auth service was up and running, and I also verified that the container was exposing port 8189.

In an attempt to address this issue, I decided to install Docker Compose version 1.29 and run the project using the `make run` command as an alternative to using the new Docker Compose plugin. Unfortunately, this approach resulted in the following error message: `ERROR: Invalid interpolation format for the "environment" option within the "auth" service: "${MG_AUTH_GRPC_SERVER_CERT:+/auth-grpc-server.crt}".` @arvindh123

and also there's no service logs being sent to the auth service when I make the request only the initial log messages ```
{"level":"info","message":"auth service http server listening at auth:8189 without TLS","ts":"2023-11-29T10:46:06.178539544Z"}
{"level":"info","message":"auth service gRPC server listening at auth:8181 without TLS","ts":"2023-11-29T10:46:06.179784455Z"}```

**Comment by arvindh123** [comment]
@ahmmkh 
`make run` was build for docker-compose v2 version which are having support for [parameter-expansion](https://docs.docker.com/compose/environment-variables/env-file/#parameter-expansion)
Could you please try the `make run` with docker-compose [v2.23.3](https://docs.docker.com/compose/release-notes/)

**Comment by nyagamunene** [comment]
@arvindh123 @dborovcanin We can have this issue closed. I have tested and the bug doesn't exist anymore.
