### ISSUE TITLE
Run tests fail

### ISSUE THREAD

**Issue by nintran52** [Mainflux/mainflux-lite#2014]
**BUG REPORT**
1. What were you trying to achieve?
- Run tests
2. What are the expected results?
- Pass all the tests
3. What are the received results?
- Some of the tests fail
4. What are the steps to reproduce the issue?
- run `make test`
5. In what environment did you encounter the issue?
- Local
6. Additional information you deem important:
- I have checked the log, and there are many testing functions that are missing mock data
![Screenshot 2023-11-11 at 16 12 55](https://github.com/mainflux/mainflux/assets/92280633/ec67b4aa-da0d-4490-909e-f2ddf083fa4a)

**Comment by drasko** [comment]
Very interesting.

@dborovcanin and @arvindh123, please take a look at this.

**Comment by dborovcanin** [comment]
We are in the middle of huge structural changes and absmach/magistrala#2024, absmach/magistrala#2017, and absmach/magistrala#2016 are related to test problems. I'm adding a bug label to this one.

> I accidentally closed the issue, this is a bug and the issue will be addressed in the PR.

**Comment by rodneyosodo** [comment]
@dborovcanin This can be closed as it is a duplicate of https://github.com/absmach/magistrala/issues/1945
