### ISSUE TITLE
Server error when logging with an invalid domain

### ISSUE THREAD

**Issue by dborovcanin** [Mainflux/mainflux-lite#2015]
**BUG REPORT**

1. What were you trying to achieve?
I am trying to log in with an invalid Domain ID.

2. What are the expected results?
I expect to receive the Unauthorized error (401).

3. What are the received results?
I get Internal Server Error (500)

4. What are the steps to reproduce the issue?
1. Register user
2. Login providing a non-existent `domain_id`
Alternatively, I get the same error in case the domain exists, but I am not the one who created it (domain admin).
The error is related to handling Auth service errors:
```
error: rpc error: code = PermissionDenied desc = failed to perform authorization over the entity : failed to perform authorization over the entity : PERMISSIONSHIP_NO_PERMISSION.","ts":...
```

5. In what environment did you encounter the issue?
The latest Magistrala running in the Docker environment.

6. Additional information you deem important:
N/A

**Comment by rodneyosodo** [comment]
This is currently solved
[![asciicast](https://asciinema.org/a/BPCv2gkVmhsrfxo5Oqnd5s89Y.svg)](https://asciinema.org/a/BPCv2gkVmhsrfxo5Oqnd5s89Y)

**Comment by nyagamunene** [comment]
@dborovcanin. We can have this closed. I have tested and the issue was solved with it give back an forbidden error 403
