### ISSUE TITLE
Fix tests and make CI pass

### ISSUE THREAD

**Issue by dborovcanin** [Mainflux/mainflux-lite#2017]
**ENHANCEMENT**
1. Describe the enhancement you are requesting.
CI is failing. We need to improve on tests and linting comments.
We need to add more tests for Domains, as well as cover for unhappy flow in other tests.

2. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).
This is a must-have.

**Comment by rodneyosodo** [comment]
Currently doing this under https://github.com/absmach/magistrala/issues/37

**Comment by dborovcanin** [comment]
@1998-felix Will take over this one. Tests that need to be updated (in respective order):
- [x] Bootstrap
- [x] Adapters
- [x] Consumers
- [x] Readers
- [x] Things
- [ ] Users
- [x] Auth
