### ISSUE TITLE
Add HTTP API for authorization

### ISSUE THREAD

**Issue by ianmuchyri** [Mainflux/mainflux-lite#2031]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Add http api endpoint for auhorization. This will be used in the sdk.
3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
must-have

**Comment by arvindh123** [comment]
@ianmuchyri 
Why we need HTTP API for Authorization in SDK ? 
Service will take care of authorization

**Comment by ianmuchyri** [comment]
> @ianmuchyri Why we need HTTP API for Authorization in SDK ? Service will take care of authorization

we need to perform authorization of a user against certain actions. For example, if a user is viewer, then we should be able to disable the edit buttons in the ui, for this we used authorize.

**Comment by arvindh123** [comment]
> > @ianmuchyri Why we need HTTP API for Authorization in SDK ? Service will take care of authorization
> 
> we need to perform authorization of a user against certain actions. For example, if a user is viewer, then we should be able to disable the edit buttons in the ui, for this we used authorize.

User permissions can be provided along with retrieve entity response or in separate endpoints 
Implementation in this PR absmach/magistrala-old#66

**Comment by dborovcanin** [comment]
@ianmuchyri Given the updates on permissions API, is this still needed?

**Comment by ianmuchyri** [comment]
> @ianmuchyri Given the updates on permissions API, is this still needed?

No need. The issue should have been closed with this comment https://github.com/absmach/magistrala/issues/2031#issuecomment-1884360675
