### ISSUE TITLE
Update Blogs for 0.14

### ISSUE THREAD

**Issue by dborovcanin** [Mainflux/mainflux-lite#2043]
It's been a while since we updated [our blogs](https://medium.com/mainflux-iot-platform). As we prepare for 0.14, we should document all the recent changes in a blog post that we can attach to the social media announcements for 0.14.

**Comment by dborovcanin** [comment]
I assigned this to @rodneyosodo. He will provide most of the content, and @1998-felix and @Musilah will help with formatting, illustrations, and the rest of the content.

**Comment by rodneyosodo** [comment]
- https://github.com/absmach/magistrala-docs/pull/175
- https://github.com/absmach/magistrala-docs/pull/177
- https://github.com/absmach/magistrala-docs/pull/176
