### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by dborovcanin** [Mainflux/mainflux-lite#2049]
Magistrala uses structured logging, but sometimes, log messages are not structured in an ideal way for searching. For example, the NOV project pointed out that we need a separate field for ThingID or ExternalID on the Bootstrap service because most likely they will need to filter logs by them.

**Comment by dborovcanin** [comment]
Also, introduce `f`-log functions for formatting: `Errorf`, `Infof`... as well as `Fatal` and `Fatalf`.

**Comment by dborovcanin** [comment]
Also, consider using structured log provided by native package: https://pkg.go.dev/log/slog.

**Comment by chombium** [comment]
Using the `slog` package will enable adding of contextual information trough slog attributes which will improve the obeservability and will speed up things when finding errors or correlating data between logs from different services. Furthermore, we could also think about adopting [OpenTelemetry Semantic Conventions](https://opentelemetry.io/docs/concepts/semantic-conventions/) to unify the naming of the attributes.

As someone asked for specific attributes, maybe we should also define a concept for custom logs and metrics labels(attributes) as well.
