### ISSUE TITLE
Bug: Unable to reset user password

### ISSUE THREAD

**Issue by VeddySama** [Mainflux/mainflux-lite#2051]
### What were you trying to achieve?

I want to reset my user password but I get an error

### What are the expected results?

Password reset successfully

### What are the received results?

{
	"error": "",
	"message": "entity not found"
}

### In what environment did you encounter the issue?

Ubuntu 22.10
Docker 24.0.5
Golang 1.21.1

**Comment by dborovcanin** [comment]
This issue has been resolved via https://github.com/absmach/magistrala/pull/2135.
