### ISSUE TITLE
Bug: List Domains not showing domains

### ISSUE THREAD

**Issue by ianmuchyri** [Mainflux/mainflux-lite#2056]
### What were you trying to achieve?

list domains

### What are the expected results?

A list of my domains

### What are the received results?

I receive an empty list:
```
{
    "total": 0,
    "offset": 0,
    "limit": 10,
    "status": "all"
}
```
I would like when I list domains with `http://localhost:8189/domains` , I should receive a list of my domains, at least the enabled ones.
Seems that when I list domains with `status=all` query parameter, I receive an empty response

### Steps To Reproduce

1. log into magistrala
2. create domain
3. list domains with `status=all`

### In what environment did you encounter the issue?

Magistrala current main branch

### Additional information you deem important
I think it is related to this https://github.com/absmach/magistrala-old/pull/248

_No response_

**Comment by dborovcanin** [comment]
@ianmuchyri Please double-check, this is supposed to be fixed. Please add a reference to the PR that fixed it.

**Comment by ianmuchyri** [comment]
It was resolved in this pr: https://github.com/absmach/magistrala-old/pull/248
However, is it suitable to list all domains by default, or should we only be listing enabled domains by default? 
@arvindh123 , @dborovcanin . This is based on this discussion: https://github.com/absmach/magistrala-old/pull/248#discussion_r1440167327

**Comment by dborovcanin** [comment]
We should list only enabled domains (also everything else) by default, if not specified otherwise.
