### ISSUE TITLE
Feature: Change Authorize to use UserID instead of Token

### ISSUE THREAD

**Issue by Musilah** [Mainflux/mainflux-lite#2065]
### Is your feature request related to a problem? Please describe.

We need to make this user ID, rather than the token. 
_Originally posted by @dborovcanin in https://github.com/absmach/magistrala-old/pull/272#discussion_r1465268996_

### Describe the feature you are requesting, as well as the possible use case(s) for it.

For this function we are required to use the UserID instead of token to authorize the subject over the object. 

```
func (svc service) Authorize(ctx context.Context, pr PolicyReq) error {
	if err := svc.PolicyValidation(pr); err != nil {
		return errors.Wrap(svcerr.ErrMalformedEntity, err)
	}
	if pr.SubjectKind == TokenKind {
		key, err := svc.Identify(ctx, pr.Subject)
		if err != nil {
			return errors.Wrap(svcerr.ErrAuthentication, err)
		}
		if key.Subject == "" {
			if pr.ObjectType == GroupType || pr.ObjectType == ThingType || pr.ObjectType == DomainType {
				return errors.ErrDomainAuthorization
			}
			return svcerr.ErrAuthentication
		}
		pr.Subject = key.Subject
		pr.Domain = key.Domain
	}
	if err := svc.checkPolicy(ctx, pr); err != nil {
		return err
	}
	return nil
}
```

### Indicate the importance of this feature to you.

Should-have

**Comment by arvindh123** [comment]
@dborovcanin  Please provide your approach guidance for this task.

**Comment by dborovcanin** [comment]
This won't be relevant as soon as a new Auth is in place, since authN and authZ are going to be separated anyways.
