### ISSUE TITLE
Feature: Rename Viewer relation to better word and having relation which can do only view not creation of entitles

### ISSUE THREAD

**Issue by arvindh123** [Mainflux/mainflux-lite#2071]
### Is your feature request related to a problem? Please describe.

Viewer relation in domain (and might also in groups) leads to misinterpretation that this relation allows to only view entities. 
But actually viewer relation allows to view relation and create new entities

### Describe the feature you are requesting, as well as the possible use case(s) for it.

Suggesting some alternative naming for present viewer Role 
This Role can able to view the entity (group) and also able to view all of its child entities (sub groups, channels, things)
This role also provide access create new entities and assign under entity (group)
 - contributor

A relation which can do only view of entities and not allowed to create entities.
 - spectator (prefers)
 - observer 
 - viewer (not preferring) 

### Indicate the importance of this feature to you.

Must-have

**Comment by dborovcanin** [comment]
Let's schedule a meeting to discuss this one and #1954 to deblock and move on.

**Comment by arvindh123** [comment]
This is similar to https://github.com/absmach/magistrala/issues/2075

**Comment by dborovcanin** [comment]
We'll call this relation **contributor**.
