### ISSUE TITLE
Feature: Policy for Domain member to restrict on creation new entities such as things, channels and groups in domain

### ISSUE THREAD

**Issue by arvindh123** [Mainflux/mainflux-lite#2075]
### Is your feature request related to a problem? Please describe.

Domain member could not restricted to create new entities such as things, channels and groups in a domain

### Describe the feature you are requesting, as well as the possible use case(s) for it.

Requesting a policy for Domain member to create new entities such as things, channels and groups in a domain

### Indicate the importance of this feature to you.

Must-have

**Comment by dborovcanin** [comment]
We need to discuss the approach before starting the implementation.

**Comment by nyagamunene** [comment]
> We need to discuss the approach before starting the implementation.

Okay

**Comment by arvindh123** [comment]
`Guest` relation, who can view only entities to which assigned.
