### ISSUE TITLE
Check if NginX Lua script is still necessary for mTLS

### ISSUE THREAD

**Issue by drasko** [Mainflux/mainflux-lite#2080]
### Is your feature request related to a problem? Please describe.

No

### Describe the feature you are requesting, as well as the possible use case(s) for it.

Can we do mTLS (and TLS termination in general) now with mProxy, without depending on NginX?

### Indicate the importance of this feature to you.

Must-have

**Comment by arvindh123** [comment]
Implementation PR in mProxy https://github.com/absmach/mproxy/pull/57
