### ISSUE TITLE
MQTT adapter does not subscribe messages from NATS, instead, it gets message directly from its own mqtt broker

### ISSUE THREAD

**Issue by Maxpeng92** [Mainflux/mainflux-lite#210]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

**BUG REPORT**

1. What were you trying to achieve?
MQTT adapter should subscribe to NATS/NATS cluster, and MQTT broker(Aedes) should not have a internal loop to send published message from clients to clients who subscribe that topic directly. 

2. What are the expected results?
The loop should look like: Publisher --> MQTT adapter (A) --> NATS/NATS cluster --> MQTT adapter (B) --> Subscriber. We should have adapter be able to scale up rather than a single point of failure.

3. What are the received results?
The current loop looks like: Publisher --> MQTT adapter (A) --> Subscriber. However, Publisher --> MQTT adapter (A),  Nothing would be received if Subscriber connects to MQTT adapter (B).

4. What are the steps to reproduce the issue?
Have 2 MQTT adapter instances running, publisher connects to A, while subscriber connects to B. Subscriber won't be able to receive message from the publisher.

5. In what environment did you encounter the issue?
Docker swarm/AWS.

6. Additional information you deem important:
In the current design, NATS is not really used for mqtt/ws communication. MQTT adapter only subscribe http message (mqtt message got filter out, otherwise you'll receive twice of the same published message) from NATS.

**Comment by drasko** [comment]
@Maxpeng92 unfortunately - this is how MQTT brokers work :). We are using off-the-shelf open-source MQTT broker, and did not fork it or change it's internals.

Of all the MQTT brokers we have tried so far, and we tried a lot, Aedes was the one with most options for config. Still - we could not prevent it to publish through it's own broker when it is publishing to NATS.

We are currently working on our custom `mqtt` adapter written in Go, which will be integrated with NATS and published soon in Mainflux official repo. This implementation will work exactly as you described - messages will flow through NATS and back to another (or same) MQTT adapter and then be published to attached clients. This way all the scaling of the MQTT service will go through NATS, and MQTT adapter will practically be stateless and thus very easy to scale.
