### ISSUE TITLE
Bug: Have a fixed unix timeformat precision in SenML 

### ISSUE THREAD

**Issue by ianmuchyri** [Mainflux/mainflux-lite#2113]
### What were you trying to achieve?

Send messages in different unix precisions and be able to process the time correctly

### What are the expected results?

I should be able to accept different precision levels since different devices produce different time precision levels. But the time stored in the database should be in a fixed precision level i.e unixNano precision.

### What are the received results?

Data is stored in the database in different precision levels depending on the precision of the time sent in the message payload.

### Steps To Reproduce

1. Run latest magistrala
2. send messages in SenML format with the message time with different unix precisions. i.e unix() -10, unixNano() -19, unixMilli() - 13
3. Try carrying out SQL queries on the data, such as aggregation, and filter with to and from, they will be affected due to the precision level being different.

### In what environment did you encounter the issue?

latest magistrala

**Comment by arvindh123** [comment]
This requires changes in Timescale DB  hypertable. 

At present TimescaleDB hypertable,  create chunks for every 86400000  increment of time `BIGINT`.

```sql 
SELECT create_hypertable('messages', 'time', create_default_indexes => FALSE, chunk_time_interval => 86400000, if_not_exists => TRUE);`,
```
https://github.com/absmach/magistrala/blob/89eaa8e09feb1af28d8298d0b19de3c882460c53/readers/timescale/init.go#L69


86400000 is equal to 1 day in Millisecond

So which mean TimescaleDB create chunks for every one day , assuming that column `time` BIGINT are in millisecond precision. 


If we store time NANO Second precision in column `time` (type: BIGINT) in database , then we should changed the create chunk interval to 86400000000000 (1 day in Nanosecond) = 86400000  x 1000000 (1 nano second in milli second precision) 

```diff
- SELECT create_hypertable('messages', 'time', create_default_indexes => FALSE, chunk_time_interval => 86400000, if_not_exists => TRUE);`,
+ SELECT create_hypertable('messages', 'time', create_default_indexes => FALSE, chunk_time_interval => 86400000000000 , if_not_exists => TRUE);`,
```
https://github.com/absmach/magistrala/blob/89eaa8e09feb1af28d8298d0b19de3c882460c53/readers/timescale/init.go#L69
