### ISSUE TITLE
Bug: Unable to enable thing using bootstrap

### ISSUE THREAD

**Issue by nyagamunene** [Mainflux/mainflux-lite#2125]
### What were you trying to achieve?

I was trying to connect a thing to the channels by using  curl request to the things service.

### What are the expected results?

The expected result is a successful response indicating that the thing has been connected to the channel.

### What are the received results?

This was the received results. When setting the state to 1 this is the result. 
![image](https://github.com/absmach/magistrala/assets/61874077/964cf48a-df5b-44b1-ae28-ac6de2cd8084)
And this is the logs from the bootstrap service.
![image](https://github.com/absmach/magistrala/assets/61874077/9f4a35cc-18d4-435b-82c8-ed3c3491725d)
And this is the logs from the things service.
![image](https://github.com/absmach/magistrala/assets/61874077/6b09bcc9-6be5-4306-a056-672067afdb29)

### Steps To Reproduce

1. Run Magistrala using command `make run`
2. Run Bootstrap service using command `make run_addons bootstrap`
3. Created new thing and channel.
4. Create bootstrap configuration of the thing and channel
5. Connect the thing to the channels using the following request:
`curl -s -S -i -X PUT -H "Authorization: Bearer <user_token>" -H "Content-Type: application/json" http://localhost:9013/things/state/<thing_id> -d '{"state": 1}'`

### In what environment did you encounter the issue?

Docker

### Additional information you deem important

This issue is preventing the thing from being connected to the channels, which is a critical functionality.For more details, Please refer below bootstrap doc
https://docs.magistrala.abstractmachines.fr/bootstrap/

**Comment by JeffMboya** [comment]
![image](https://github.com/absmach/magistrala/assets/44696487/09cd32c1-2fba-4be1-b13d-1081291aa040)
If the connection between the 'thing_id' and 'channel_id' was established through the User Interface (UI), then the disconnection should also be performed through the UI. Similarly, if the connection was established using the `curl` command in the terminal, the disconnection should also be executed using a `curl` command in the terminal. 

As it stands, there is no interchangeability between the two methods. In other words, a connection made through the UI cannot be disconnected using a `curl` command in the terminal, and vice versa. Each method of connection requires its corresponding method of disconnection.

**Comment by JeffMboya** [comment]
Actually, the two methods are interchangeable and the error is as a result of poor error handling in bootstrap when you try to connect a thing that is already connected to a channel. A more intuitive output would be one that let's the user know the connection already exists or simply return an OK

![image](https://github.com/absmach/magistrala/assets/44696487/b6855360-aca7-44a6-92b0-2684f1228dd2)
