### ISSUE TITLE
Rename Mainflux to Magistrala in HELM charts

### ISSUE THREAD

**Issue by JeffMboya** [Mainflux/mainflux-lite#2141]
### Is your feature request related to a problem? Please describe.

No

### Describe the feature you are requesting, as well as the possible use case(s) for it.

Rename "Mainflux" to "Magistrala" in HELM charts. This will make the naming more consistent.

### Indicate the importance of this feature to you.

Must-have

**Comment by arvindh123** [comment]
Issue created in devops repo https://github.com/absmach/devops/issues/130
