### ISSUE TITLE
Consume Things connect event in Bootstrap

### ISSUE THREAD

**Issue by JeffMboya** [Mainflux/mainflux-lite#2142]
### Is your feature request related to a problem? Please describe.

Currently, Bootstrap ```events.go``` handles ```removeEvent```, ```updateChannelEvent```, and ```disconnectEvent``` in the ```consumer``` package. However, we do not have a mechanism to consume a ```connectEvent``` when a Thing connect event

### Describe the feature you are requesting, as well as the possible use case(s) for it.

Addition of a ```connectEvent``` struct in the ```consumer``` package. This struct would contain the ```thingID``` and ```channelID```, similar to the ```disconnectEvent``` shown below. This event would be triggered whenever a Thing connects to the system.
![image](https://github.com/absmach/magistrala/assets/44696487/d7b47a33-30c3-4355-9c4d-5726346fd3d2)

### Indicate the importance of this feature to you.

Must-have

### Anything else?

Here's a rough idea of what the independent `connectEvent` struct might look like:

```go
type connectEvent struct {
	thingID   string
	channelID string
}
```

Alternatively, define a connection event that consumes both ```Thing connect``` and ```Thing disconnect``` as below:
```go
type connectionEvent struct {
	chanID  string
	thingID string
}

func decodeConnectionThing(event map[string]interface{}) connectionThingEvent {
	return connectionThingEvent{
		chanID:  read(event, "chan_id", ""),
		thingID: read(event, "thing_id", ""),
	}
func (es *eventHandler) Handle(ctx context.Context, event events.Event) error {
	msg, err := event.Encode()
	if err != nil {
		return err
	}
	switch msg["operation"] {
	case thingConnect:
		tce := decodeConnectionThing(msg)
		err = es.svc.ConnectThing(ctx, tce.chanID, tce.thingID)
	case thingDisconnect:
		tde := decodeConnectionThing(msg)
		err = es.svc.DisconnectThing(ctx, tde.chanID, tde.thingID)
	}
	if err != nil && err != errMetadataType {
		return err
	}

	return nil
}
```
This feature request is based on the current code in the `consumer` package:

**Comment by dborovcanin** [comment]
This is related to #1955.
