### ISSUE TITLE
Feature: Need to delete things and channels

### ISSUE THREAD

**Issue by andychao217** [Mainflux/mainflux-lite#2169]
### Is your feature request related to a problem? Please describe.

I can add and update things and channels, but I can't find a way to delete them, it's not right

### Describe the feature you are requesting, as well as the possible use case(s) for it.

I can add and update things and channels, but I can't find a way to delete them, it's not right

### Indicate the importance of this feature to you.

Must-have

**Comment by andychao217** [comment]
i can't find APIs for them

**Comment by dborovcanin** [comment]
Hello, @andychao217. Currently, we do not support it due to the complex implication removal may cause in the system. You can, however, disable things: https://docs.api.magistrala.abstractmachines.fr/?urls.primaryName=things.yml#/Things/disableThing

**Comment by dborovcanin** [comment]
Also, please check here: https://docs.api.magistrala.abstractmachines.fr/?urls.primaryName=things.yml#/Things/delete_things__thingID_, we even support the actual hard removal.
