### ISSUE TITLE
Simplify Magistrala core repository 

### ISSUE THREAD

**Issue by dborovcanin** [Mainflux/mainflux-lite#2187]
### Is your feature request related to a problem? Please describe.

No, it is not, except for maintenance difficulties.

### Describe the feature you are requesting, as well as the possible use case(s) for it.

Due to the amount of time and effort to maintain services that many people do not use, we decided to move those services from the Magistrala core repository to a new home: https://github.com/absmach/contrib.
Code in this repository will be provided as-is, with no guarantee that Maigstrala maintainers will keep it up to date, tested, and at the high-quality standards we aim to preserve in the core repo. This new repository will also be used for experimental new features and services, and as a place for the community to send new interesting Magistrala plugins. Services and code that will be moved from the core include:
- Twins
- Cassandra reader and writer
- MongoDB reader and writer
- Notifiers
- Tools

We still need to decide about:
- Bootstrap
- Postgres reader and writer
- LoRA
- OPC-UA
- Certs
- Provision

### Indicate the importance of this feature to you.

Must-have

### Anything else?

This will include changes in the docs, CI scripts, Make scripts, links and references, and all the other relevant places.

**Comment by arvindh123** [comment]
@dborovcanin  
We can have provision in core, by improving it features. 
But It should not conflict with API Gateway.
