### ISSUE TITLE
Feature: Delete multiple policies with relationship filters

### ISSUE THREAD

**Issue by arvindh123** [Mainflux/mainflux-lite#2198]
### Is your feature request related to a problem? Please describe.

Could not delete policy with array of relationship filters
like delete [things of users1 , things of user 2, things of user 3 ]

### Describe the feature you are requesting, as well as the possible use case(s) for it.

At present `DeletePolicy` gRPC support delete policy with relationship filter for one policy 
It should made into array. 

### Indicate the importance of this feature to you.

Must-have

### Anything else?

Rename the function to `DeleteFilterPolicies`

**Comment by arvindh123** [comment]
@absmach/magistrala  

Auth Policies are backed by SpiceDB, In spiceDB they supports one policy per request for Delete relations with filter.
So this feature is not feasible for now. 

We can rename the `DeletePolicy` to some other name like `DeletePolicyWithFilter`

**Comment by arvindh123** [comment]
Renaming via https://github.com/absmach/magistrala/issues/2216

**Comment by dborovcanin** [comment]
This is not possible due to AuthZed API limitations. Closing this one.
