### ISSUE TITLE
Feature: Remove unused errors variables from all error packages (svcerr, repoerr)  

### ISSUE THREAD

**Issue by arvindh123** [Mainflux/mainflux-lite#2200]
### Is your feature request related to a problem? Please describe.

Some of the error variable in repo error `pkg/errors/repository/types.go` are not used anywhere in code

### Describe the feature you are requesting, as well as the possible use case(s) for it.

Remove unused error variable in repo error `pkg/errors/repository/types.go` are not used anywhere in code

### Indicate the importance of this feature to you.

Should-have

**Comment by rodneyosodo** [comment]
Resolved by https://github.com/absmach/magistrala/pull/2243
