### ISSUE TITLE
Feature: Remove all user domain related policy on domain unassign 

### ISSUE THREAD

**Issue by arvindh123** [Mainflux/mainflux-lite#2281]
### Is your feature request related to a problem? Please describe.

Yes, 
If user is unassign and assigns back to domain, User hold all the same relation between all entities in domain

Example: 

`user_id_1` is member of `domain_id_1` 

`user_id_1` is administrator of thing_id_1, channel_id_1  
`user_id_1` is editor of group_id_1, group_id_2, group_id_3

When `user_id_1` is unassigned from `domain_id_1` and assigns back to `domain_id_1`.
After assigning again `user_id_1` to `domain_id_1` ,  `user_id_1` regains the same old permission which `user_id_1` had before unassign.
`user_id_1` have same old permissions
user_id_1 is administrator of thing_id_1, channel_id_1, 
user_id_1 is editor of group_id_1, group_id_2, group_id_3

### Describe the feature you are requesting, as well as the possible use case(s) for it.

On user unassign from domain, we need to remove all domain policies related to user. 

### Indicate the importance of this feature to you.

Must-have

**Comment by dborovcanin** [comment]
@felixgateru What's the status with this one?

**Comment by felixgateru** [comment]
> @felixgateru What's the status with this one?

Currently testing the fix.
