### ISSUE TITLE
Feature: Move auth to middleware in things service

### ISSUE THREAD

**Issue by felixgateru** [Mainflux/mainflux-lite#2415]
### Is your feature request related to a problem? Please describe.

Related to issue https://github.com/absmach/magistrala/issues/2028

### Describe the feature you are requesting, as well as the possible use case(s) for it.

Move existing auth implementation to middleware for the things service

### Indicate the importance of this feature to you.

Must-have

**Comment by dborovcanin** [comment]
It was resolved by #2424.
