### ISSUE TITLE
Consider using Protobuf linter

### ISSUE THREAD

**Issue by dborovcanin** [Mainflux/mainflux-lite#2483]
List of Proto Linters 

- https://github.com/yoheimuta/protolint
- https://github.com/ckaznocha/protoc-gen-lint
- https://buf.build/docs/lint/tutorial/ (https://dev.to/themayurkumbhar/linting-proto-files-with-buf-1fgl) 
- https://github.com/pbufio/pbuf-cli

**Comment by JeffMboya** [comment]
@dborovcanin so I have tried `protoc-gen-lint` and I get this in the error log:
```
auth.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-lint hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.
```
So I switched to `protolint` which supports optional fields in proto 3. I ahve added it to the CI here: https://github.com/absmach/magistrala/pull/2532
