### ISSUE TITLE
Bug: List domain members as super admin does not work

### ISSUE THREAD

**Issue by WashingtonKK** [Mainflux/mainflux-lite#2556]
### What were you trying to achieve?

List domain members as admin user.

### What are the expected results?

Domain members should be listed.

### What are the received results?

Authorization error.

### Steps To Reproduce

List domain members as super admin.

### In what environment did you encounter the issue?

magistrala

**Comment by dborovcanin** [comment]
Fixed via https://github.com/absmach/supermq/pull/2558.
