### ISSUE TITLE
Bug: ObjectKind missing when creating subgroup

### ISSUE THREAD

**Issue by VeddySama** [Mainflux/mainflux-lite#2587]
### What were you trying to achieve?

Solve the problem of error when adding a subgroup

### What are the expected results?

Group added successfully

### What are the received results?

Failed to add policies

### Steps To Reproduce

http://localhost:9004/{domainID}/groups
```
{
    "name": "ChildrenGroup",
    "description": "children group",
    "parent_id": "8a7fe2bb-fdf1-4d1d-850a-27961ec2f85e"
}
```

### In what environment did you encounter the issue?

In the latest version

### Additional information you deem important

The specific problem occurs when the parent_id parameter is included when creating a group, ObjectKind is missing when adding a policy, resulting in the switch judgment of default in the groupPreConditions method of spicedb.
The specific problem occurs in the following files:
groups/service.go:93
pkg/policies/spicedb/service.go:814

**Comment by VeddySama** [comment]
There is an additional problem. When using the http://localhost:9004/{domainID}/groups/{groupID}/hierarchy?tree=true interface and transmitting the parameter tree=true, no tree structure is returned. The group that is not allowed to access will be reset to Group{ID: "xxxx-xxxx-xxxx-xxxx", Level: g.Level}, which is not the expected effect.
`{
			"id": "xxxx-xxxx-xxxx-xxxx",
			"name": "",
			"level": 2,
			"created_at": "0001-01-01T00:00:00Z",
			"updated_at": "0001-01-01T00:00:00Z",
			"status": "enabled"
		},`

**Comment by dborovcanin** [comment]
@VeddySama Thanks for reporting, this issue should be resolved now. Please try pulling the latest images and let us know if you have any other issues.
